# -*- mode: org -*-
#+DATE: 2016-01-27
#+TITLE: Specifications of a Program that Synchronizes Directories
#+AUTHOR: Prabhaker Mateti
#+DESCRIPTION: Software Engineering
#+HTML_LINK_UP: ../
#+HTML_LINK_HOME: ../../
#+HTML_HEAD: <style> P {text-align: justify} code, pre {color: brown;} @media screen {BODY {margin: 10%} }</style>
#+BIND: org-html-preamble-format (("en" "<a href=\"../../\"> ../../</a>"))
#+BIND: org-html-postamble-format (("en" "<hr size=1>Copyright &copy; 2016 %e &bull; <a href=\"http://www.wright.edu/~pmateti\"> www.wright.edu/~pmateti</a>  %d"))
#+STARTUP:showeverything
#+OPTIONS: toc:2

Abstract: We outline how the dirsync program can be specified
rigorously and unambiguously.  This note is Work-in-Progress.

* What is a File Volume?

** Files

A file is an association of two things, a name and a content, managed
by the OS.  There are at least two kinds of files we must focus in the
context of dir sync: directories and ordinary (i.e., non-dir) files.

** Directories

The typical view is that a /directory/ is a tree, in CS text books.
In graph theory this becomes a rooted, directed acyclic graph,
assuming no hard links or sym links.  The non-leaf nodes must be
directories.  Some, not necessarily all, leaf nodes are ordinary
files.  Note that there is no order among the edges emanating from a
node.

Taking practical view, a directory is a table of two columns: file
names, and an "iNumber".  An i# is a positive integer used as an
argument to a mapping named /inode/; thus inode(5) yields many details
of the named in that row of the directory table.  This
design/implementation of thus mapping varies widely (wildely?) across
OSs.  Even the file names obey different rules in different OSs.

** Absolute Path names


** Relative Path names



* Time Stamps on Different Systems
* Deep Equality of Directories

* References

1. DirSync manual
1. William A. Slough, and Prabhaker Mateti, "Functional Specifications
   of a Hierarchical File System," Fifteenth Hawaii International
   Conference on System Sciences, 210-217, Jan 1982.
