Game-of-Life-WSU-CEG4180: org.bitstorm.util.AboutDialog Class Reference
org.bitstorm.util.AboutDialog Class Reference
Public Member Functions
AboutDialog (Frame parent, String title, String[] lines, String imageName, int posX, int posY)
void processEvent (AWTEvent e)
Private Member Functions
void close ()
Private Attributes
Button okButton
Detailed Description
Shows a constructed About dialog box. The dialog box can contain an image and several lines of text.
Author
Edwin Martin
Definition at line 28 of file AboutDialog.java.
Constructor & Destructor Documentation
org.bitstorm.util.AboutDialog.AboutDialog (Frame parent, String title, String[] lines, String imageName, int posX, int posY)
Construct a AboutDialog.
Parameters
parent parent Frame
title title of dialog
imageName image to show
posX x-coordinate
posY y-coordinate
Definition at line 39 of file AboutDialog.java.
References org.bitstorm.util.AboutDialog.close().
{
         super( parent, title, false );
         Image image = Toolkit.getDefaultToolkit().getImage(this.getClass().getResource(imageName));
     ImageComponent ic = new ImageComponent( image );
     okButton = new Button("   OK   ");
     okButton.addActionListener(
       new ActionListener() {
         public void actionPerformed(ActionEvent e) {
           close();
         }
       }
     );
         GridBagLayout gridbag = new GridBagLayout();
         GridBagConstraints contraints = new GridBagConstraints();
         setLayout(gridbag);
         Panel buttonPanel = new Panel();
     buttonPanel.setLayout( new FlowLayout( FlowLayout.CENTER ) );
     buttonPanel.add( okButton );
     Panel textPanel = new Panel();
     textPanel.setLayout( new GridLayout( lines.length, 1 ) );
     for (int i=0; i<lines.length; i++) {
       textPanel.add(new Label(lines[i]));
     }
     contraints.fill = GridBagConstraints.BOTH;
     contraints.weightx = 1;
         contraints.weighty = 1;
         contraints.gridx = GridBagConstraints.REMAINDER;
         contraints.gridy = 0;
         contraints.anchor = GridBagConstraints.CENTER;
         gridbag.setConstraints(ic, contraints);
     add( ic );
     contraints.fill = GridBagConstraints.NONE;
         contraints.weightx = 0;
         contraints.weighty = 0;
         contraints.gridy = 1;
         gridbag.setConstraints(textPanel, contraints);
     add( textPanel );
         contraints.gridy = 2;
         gridbag.setConstraints(buttonPanel, contraints);
     add( buttonPanel );
     enableEvents(Event.WINDOW_DESTROY);
     setResizable( false );
     setModal( true );
     pack();
     setLocation( posX, posY );
     show();
     }
Member Function Documentation
void org.bitstorm.util.AboutDialog.close () private
Close dialog box.
Definition at line 95 of file AboutDialog.java.
Referenced by org.bitstorm.util.AboutDialog.AboutDialog(), and org.bitstorm.util.AboutDialog.processEvent().
{
         this.hide();
         this.dispose();
     }
void org.bitstorm.util.AboutDialog.processEvent (AWTEvent e)
Process close window button.
See also
java.awt.Component::processEvent(java.awt.AWTEvent)
Definition at line 103 of file AboutDialog.java.
References org.bitstorm.util.AboutDialog.close().
{
     if ( e.getID() == Event.WINDOW_DESTROY )
       close();
   }
Member Data Documentation
Button org.bitstorm.util.AboutDialog.okButton private
Definition at line 29 of file AboutDialog.java.
The documentation for this class was generated from the following file:
AboutDialog.java