Game-of-Life-WSU-CEG4180: org.bitstorm.gameoflife.CellGridCanvas Class Reference
org.bitstorm.gameoflife.CellGridCanvas Class Reference
Public Member Functions
CellGridCanvas (CellGrid cellGrid, int cellSize)
void setCellSize (int cellSize)
void resized ()
void saveCellUnderMouse (int x, int y)
void draw (int x, int y)
void update (Graphics g)
void paint (Graphics g)
Dimension getPreferredSize ()
Dimension getMinimumSize ()
void setAfterWindowResize (Shape newShape, int newCellSize)
synchronized void setShape (Shape shape) throws ShapeException
Private Attributes
boolean cellUnderMouse
Image offScreenImage
Graphics offScreenGraphics
Image offScreenImageDrawed
Graphics offScreenGraphicsDrawed
int cellSize
CellGrid cellGrid
Vector listeners
int newCellSize
Shape newShape
Detailed Description
Subclass of Canvas, which makes the cellgrid visible. Communicates via CellGrid interface.
Author
Edwin Martin
Definition at line 28 of file CellGridCanvas.java.
Constructor & Destructor Documentation
org.bitstorm.gameoflife.CellGridCanvas.CellGridCanvas (CellGrid cellGrid, int cellSize)
Constructs a CellGridCanvas.
Parameters
cellGrid the GoL cellgrid
cellSize size of cell in pixels
Definition at line 51 of file CellGridCanvas.java.
References org.bitstorm.gameoflife.CellGridCanvas.cellGrid, org.bitstorm.gameoflife.CellGridCanvas.cellSize, org.bitstorm.gameoflife.CellGridCanvas.draw(), org.bitstorm.gameoflife.CellGridCanvas.resized(), and org.bitstorm.gameoflife.CellGridCanvas.saveCellUnderMouse().
{
     this.cellGrid = cellGrid;
     this.cellSize = cellSize;
     setBackground(new Color(0x999999));
     addMouseListener(
       new MouseAdapter() {
         public void mouseReleased(MouseEvent e) {
           draw(e.getX(), e.getY());
         }
         public void mousePressed(MouseEvent e) {
           saveCellUnderMouse(e.getX(), e.getY());
         }
       });
     addMouseMotionListener(new MouseMotionAdapter() {
       public void mouseDragged(MouseEvent e) {
         draw(e.getX(), e.getY());
       }
     });
     addComponentListener(
       new ComponentListener() {
         public void componentResized(ComponentEvent e) {
           resized();
           repaint();
         }
         public void componentMoved(ComponentEvent e) {}
         public void componentHidden(ComponentEvent e) {}
         public void componentShown(ComponentEvent e) {}
       }
     );
   }
Member Function Documentation
void org.bitstorm.gameoflife.CellGridCanvas.draw (int x, int y)
Draw in this cell.
Parameters
x x-coordinate
y y-coordinate
Definition at line 139 of file CellGridCanvas.java.
References org.bitstorm.gameoflife.CellGrid.setCell().
Referenced by org.bitstorm.gameoflife.CellGridCanvas.CellGridCanvas().
{
     try {
       cellGrid.setCell(x / cellSize, y / cellSize, !cellUnderMouse );
       repaint();
     } catch (java.lang.ArrayIndexOutOfBoundsException e) {
       // ignore
     }
   }
Dimension org.bitstorm.gameoflife.CellGridCanvas.getMinimumSize ()
This is the minimum size (size of one cell).
See also
java.awt.Component::getMinimumSize()
Definition at line 210 of file CellGridCanvas.java.
{
     return new Dimension( cellSize,  cellSize );
   }
Dimension org.bitstorm.gameoflife.CellGridCanvas.getPreferredSize ()
This is the preferred size.
See also
java.awt.Component::getPreferredSize()
Definition at line 201 of file CellGridCanvas.java.
References org.bitstorm.gameoflife.CellGrid.getDimension().
{
     Dimension dim = cellGrid.getDimension();
     return new Dimension( cellSize * dim.width,  cellSize * dim.height );
   }
void org.bitstorm.gameoflife.CellGridCanvas.paint (Graphics g)
Draw this generation.
See also
java.awt.Component::paint(java.awt.Graphics)
Definition at line 166 of file CellGridCanvas.java.
References org.bitstorm.gameoflife.Cell.col, org.bitstorm.gameoflife.CellGrid.getDimension(), org.bitstorm.gameoflife.CellGrid.getEnum(), and org.bitstorm.gameoflife.Cell.row.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.update().
{
     // Draw grid on background image, which is faster
     if (offScreenImageDrawed == null) {
       Dimension dim = cellGrid.getDimension();
       Dimension d = getSize();
       offScreenImageDrawed = createImage(d.width, d.height);
       offScreenGraphicsDrawed = offScreenImageDrawed.getGraphics();
       // draw background (MSIE doesn't do that)
       offScreenGraphicsDrawed.setColor(getBackground());
       offScreenGraphicsDrawed.fillRect(0, 0, d.width, d.height);
       offScreenGraphicsDrawed.setColor(Color.gray);
       offScreenGraphicsDrawed.fillRect(0, 0, cellSize * dim.width - 1, cellSize * dim.height - 1);
       offScreenGraphicsDrawed.setColor(getBackground());
       for (int x = 1; x < dim.width; x++) {
         offScreenGraphicsDrawed.drawLine(x * cellSize - 1, 0, x * cellSize - 1, cellSize * dim.height - 1);
       }
       for (int y = 1; y < dim.height; y++) {
         offScreenGraphicsDrawed.drawLine( 0, y * cellSize - 1, cellSize * dim.width - 1, y * cellSize - 1);
       }
     }
     g.drawImage(offScreenImageDrawed, 0, 0, null);
     // draw populated cells
     g.setColor(Color.yellow);
     Enumeration enum = cellGrid.getEnum();
     Cell c;
     while ( enum.hasMoreElements() ) {
       c = (Cell)enum.nextElement();
       g.fillRect(c.col * cellSize, c.row * cellSize, cellSize - 1, cellSize - 1);
     }
   }
void org.bitstorm.gameoflife.CellGridCanvas.resized ()
The grid is resized (by window resize or zooming). Also apply post-resize properties when necessary
Definition at line 100 of file CellGridCanvas.java.
References org.bitstorm.gameoflife.CellGridCanvas.newCellSize, org.bitstorm.gameoflife.CellGrid.resize(), and org.bitstorm.gameoflife.CellGridCanvas.setShape().
Referenced by org.bitstorm.gameoflife.CellGridCanvas.CellGridCanvas(), and org.bitstorm.gameoflife.CellGridCanvas.setCellSize().
{
     if ( newCellSize != 0 ) {
       cellSize = newCellSize;
       newCellSize = 0;
     }
     Dimension canvasDim = this.size();
     offScreenImage = null;
     offScreenImageDrawed = null;
     cellGrid.resize(canvasDim.width/cellSize, canvasDim.height/cellSize);
     if ( newShape != null ) {
       try {
         setShape( newShape );
       } catch (ShapeException e) {
         // ignore
       }
     }
   }
void org.bitstorm.gameoflife.CellGridCanvas.saveCellUnderMouse (int x, int y)
Remember state of cell for drawing.
Parameters
x x-coordinate
y y-coordinate
Definition at line 125 of file CellGridCanvas.java.
References org.bitstorm.gameoflife.CellGrid.getCell().
Referenced by org.bitstorm.gameoflife.CellGridCanvas.CellGridCanvas().
{
     try {
       cellUnderMouse = cellGrid.getCell(x / cellSize, y / cellSize);
     } catch (java.lang.ArrayIndexOutOfBoundsException e) {
       // ignore
     }
   }
void org.bitstorm.gameoflife.CellGridCanvas.setAfterWindowResize (Shape newShape, int newCellSize)
Settings to appy after a window-resize.
Parameters
newShape new shape
newCellSize new cellSize
Definition at line 219 of file CellGridCanvas.java.
References org.bitstorm.gameoflife.CellGridCanvas.newCellSize, and org.bitstorm.gameoflife.CellGridCanvas.newShape.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
{
     this.newShape = newShape;
     this.newCellSize = newCellSize;
   }
void org.bitstorm.gameoflife.CellGridCanvas.setCellSize (int cellSize)
Set cell size (zoom factor)
Parameters
cellSize Size of cell in pixels
Definition at line 90 of file CellGridCanvas.java.
References org.bitstorm.gameoflife.CellGridCanvas.cellSize, and org.bitstorm.gameoflife.CellGridCanvas.resized().
Referenced by org.bitstorm.gameoflife.GameOfLife.setCellSize().
{
     this.cellSize = cellSize;
     resized();
     repaint();
   }
synchronized void org.bitstorm.gameoflife.CellGridCanvas.setShape (Shape shape) throws ShapeException
Draws shape in grid.
Parameters
shape name of shape
Returns
true when shape fits, false otherwise
Exceptions
ShapeException if the shape does not fit on the canvas
Definition at line 231 of file CellGridCanvas.java.
References org.bitstorm.gameoflife.CellGrid.clear(), org.bitstorm.gameoflife.CellGrid.getDimension(), and org.bitstorm.gameoflife.CellGrid.setCell().
Referenced by org.bitstorm.gameoflife.CellGridCanvas.resized(), org.bitstorm.gameoflife.GameOfLife.setShape(), and org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
{
     int xOffset;
     int yOffset;
     int[][] shapeGrid;
     Dimension dimShape;
     Dimension dimGrid;
     int i;
     // get shape properties
     //shapeGrid = shape.getShape();
     dimShape =  shape.getDimension();
     dimGrid =  cellGrid.getDimension();
     if (dimShape.width > dimGrid.width || dimShape.height > dimGrid.height)
       throw new ShapeException( "Shape doesn't fit on canvas (grid: "+dimGrid.width+"x"+dimGrid.height+", shape: "+dimShape.width+"x"+dimShape.height+")"); // shape doesn't fit on canvas
     // center the shape
     xOffset = (dimGrid.width - dimShape.width) / 2;
     yOffset = (dimGrid.height - dimShape.height) / 2;
     cellGrid.clear();
     // draw shape
     Enumeration cells = shape.getCells();
     while (cells.hasMoreElements()) {
       int[] cell = (int[]) cells.nextElement();
       cellGrid.setCell(xOffset + cell[0], yOffset + cell[1], true);
     }
   }
void org.bitstorm.gameoflife.CellGridCanvas.update (Graphics g)
Use double buffering.
See also
java.awt.Component::update(java.awt.Graphics)
Definition at line 152 of file CellGridCanvas.java.
References org.bitstorm.gameoflife.CellGridCanvas.paint().
{
     Dimension d = getSize();
     if ((offScreenImage == null)) {
       offScreenImage = createImage(d.width, d.height);
       offScreenGraphics = offScreenImage.getGraphics();
     }
     paint(offScreenGraphics);
     g.drawImage(offScreenImage, 0, 0, null);
   }
Member Data Documentation
CellGrid org.bitstorm.gameoflife.CellGridCanvas.cellGrid private
Definition at line 41 of file CellGridCanvas.java.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.CellGridCanvas().
int org.bitstorm.gameoflife.CellGridCanvas.cellSize private
Definition at line 40 of file CellGridCanvas.java.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.CellGridCanvas(), and org.bitstorm.gameoflife.CellGridCanvas.setCellSize().
boolean org.bitstorm.gameoflife.CellGridCanvas.cellUnderMouse private
Definition at line 29 of file CellGridCanvas.java.
Vector org.bitstorm.gameoflife.CellGridCanvas.listeners private
Definition at line 42 of file CellGridCanvas.java.
int org.bitstorm.gameoflife.CellGridCanvas.newCellSize private
Definition at line 43 of file CellGridCanvas.java.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.resized(), and org.bitstorm.gameoflife.CellGridCanvas.setAfterWindowResize().
Shape org.bitstorm.gameoflife.CellGridCanvas.newShape private
Definition at line 44 of file CellGridCanvas.java.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.setAfterWindowResize().
Graphics org.bitstorm.gameoflife.CellGridCanvas.offScreenGraphics private
Definition at line 34 of file CellGridCanvas.java.
Graphics org.bitstorm.gameoflife.CellGridCanvas.offScreenGraphicsDrawed private
Image, containing the drawed grid.
Definition at line 39 of file CellGridCanvas.java.
Image org.bitstorm.gameoflife.CellGridCanvas.offScreenImage private
Image for double buffering, to prevent flickering.
Definition at line 33 of file CellGridCanvas.java.
Image org.bitstorm.gameoflife.CellGridCanvas.offScreenImageDrawed private
Definition at line 35 of file CellGridCanvas.java.
The documentation for this class was generated from the following file:
CellGridCanvas.java