Game-of-Life-WSU-CEG4180: org.bitstorm.gameoflife.GameOfLifeControls Class Reference
org.bitstorm.gameoflife.GameOfLifeControls Class Reference
Public Member Functions
GameOfLifeControls ()
void addGameOfLifeControlsListener (GameOfLifeControlsListener listener)
void removeGameOfLifeControlsListener (GameOfLifeControlsListener listener)
void setGeneration (int generations)
void start ()
void stop ()
void startStopButtonClicked ()
void nextButtonClicked ()
void speedChanged (int speed)
void zoomChanged (int zoom)
void shapeSelected (String shapeName)
void setZoom (String n)
Static Public Attributes
static final String SLOW = "Slow"
static final String FAST = "Fast"
static final String HYPER = "Hyper"
static final String BIG = "Big"
static final String MEDIUM = "Medium"
static final String SMALL = "Small"
static final int SIZE_BIG = 11
static final int SIZE_MEDIUM = 7
static final int SIZE_SMALL = 3
Private Attributes
Label genLabel
final String genLabelText = "Generations: "
final String nextLabelText = "Next"
final String startLabelText = "Start"
final String stopLabelText = "Stop"
Button startstopButton
Button nextButton
Vector listeners
Choice shapesChoice
Choice zoomChoice
Detailed Description
GUI-controls of the Game of Life. It contains controls like Shape, zoom and speed selector, next and start/stop-button. It is a seperate class, so it can be replaced by another implementation for e.g. mobile phones or PDA's. Communicates via the GameOfLifeControlsListener.
Author
Edwin Martin
Definition at line 32 of file GameOfLifeControls.java.
Constructor & Destructor Documentation
org.bitstorm.gameoflife.GameOfLifeControls.GameOfLifeControls ()
Contructs the controls.
Definition at line 56 of file GameOfLifeControls.java.
References org.bitstorm.gameoflife.Shape.getName(), org.bitstorm.gameoflife.ShapeCollection.getShapes(), org.bitstorm.gameoflife.GameOfLifeControls.nextButtonClicked(), org.bitstorm.gameoflife.GameOfLifeControls.shapeSelected(), org.bitstorm.gameoflife.GameOfLifeControls.speedChanged(), org.bitstorm.gameoflife.GameOfLifeControls.startStopButtonClicked(), and org.bitstorm.gameoflife.GameOfLifeControls.zoomChanged().
{
     listeners = new Vector();
     // pulldown menu with shapes
     shapesChoice = new Choice();
     // Put names of shapes in menu
     Shape[] shapes = ShapeCollection.getShapes();
     for ( int i = 0; i < shapes.length; i++ )
       shapesChoice.addItem( shapes[i].getName() );
     // when shape is selected
     shapesChoice.addItemListener(
       new ItemListener() {
         public void itemStateChanged(ItemEvent e) {
           shapeSelected( (String) e.getItem() );
         }
       }
     );
     // pulldown menu with speeds
     Choice speedChoice = new Choice();
     // add speeds
     speedChoice.addItem(SLOW);
     speedChoice.addItem(FAST);
     speedChoice.addItem(HYPER);
     // when item is selected
     speedChoice.addItemListener(
       new ItemListener() {
         public void itemStateChanged(ItemEvent e) {
           String arg = (String) e.getItem();
           if (SLOW.equals(arg)) // slow
             speedChanged(1000);
           else if (FAST.equals(arg)) // fast
             speedChanged(100);
           else if (HYPER.equals(arg)) // hyperspeed
             speedChanged(10);
         }
       }
     );
     // pulldown menu with speeds
     zoomChoice = new Choice();
     // add speeds
     zoomChoice.addItem(BIG);
     zoomChoice.addItem(MEDIUM);
     zoomChoice.addItem(SMALL);
     // when item is selected
     zoomChoice.addItemListener(
       new ItemListener() {
         public void itemStateChanged(ItemEvent e) {
           String arg = (String) e.getItem();
           if (BIG.equals(arg))
             zoomChanged(SIZE_BIG);
           else if (MEDIUM.equals(arg))
             zoomChanged(SIZE_MEDIUM);
           else if (SMALL.equals(arg))
             zoomChanged(SIZE_SMALL);
         }
       }
     );
     // number of generations
     genLabel = new Label(genLabelText+"         ");
     // start and stop buttom
     startstopButton = new Button(startLabelText);
     // when start/stop button is clicked
     startstopButton.addActionListener(
       new ActionListener() {
         public void actionPerformed(ActionEvent e) {
           startStopButtonClicked();
         }
       }
     );
     // next generation button
     nextButton = new Button(nextLabelText);
     // when next button is clicked
     nextButton.addActionListener(
       new ActionListener() {
         public void actionPerformed(ActionEvent e) {
           nextButtonClicked();
         }
       }
     );
     // create panel with controls
     this.add(shapesChoice);
     this.add(nextButton);
     this.add(startstopButton);
     this.add(speedChoice);
     this.add(zoomChoice);
     this.add(genLabel);
     this.validate();
   }
Member Function Documentation
void org.bitstorm.gameoflife.GameOfLifeControls.addGameOfLifeControlsListener (GameOfLifeControlsListener listener)
Add listener for this control
Parameters
listener Listener object
Definition at line 164 of file GameOfLifeControls.java.
Referenced by org.bitstorm.gameoflife.GameOfLife.init(), and org.bitstorm.gameoflife.StandaloneGameOfLife.init().
{
     listeners.addElement( listener );
   }
void org.bitstorm.gameoflife.GameOfLifeControls.nextButtonClicked ()
Called when the next-button is clicked. Notify event-listeners.
Definition at line 216 of file GameOfLifeControls.java.
Referenced by org.bitstorm.gameoflife.GameOfLifeControls.GameOfLifeControls().
{
     GameOfLifeControlsEvent event = new GameOfLifeControlsEvent( this );
     for ( Enumeration e = listeners.elements(); e.hasMoreElements(); )
       ((GameOfLifeControlsListener) e.nextElement()).nextButtonClicked( event );
   }
void org.bitstorm.gameoflife.GameOfLifeControls.removeGameOfLifeControlsListener (GameOfLifeControlsListener listener)
Remove listener from this control
Parameters
listener Listener object
Definition at line 172 of file GameOfLifeControls.java.
{
     listeners.removeElement( listener );
   }
void org.bitstorm.gameoflife.GameOfLifeControls.setGeneration (int generations)
Set the number of generations in the control bar.
Parameters
generations number of generations
Definition at line 180 of file GameOfLifeControls.java.
Referenced by org.bitstorm.gameoflife.GameOfLife.showGenerations().
{
     genLabel.setText(genLabelText + generations + "         ");
   }
void org.bitstorm.gameoflife.GameOfLifeControls.setZoom (String n)
Called when a new cell size from the zoom pull down is selected. Notify event-listeners.
Definition at line 256 of file GameOfLifeControls.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
{
     zoomChoice.select(n);
   }
void org.bitstorm.gameoflife.GameOfLifeControls.shapeSelected (String shapeName)
Called when a new shape from the shape pull down is selected. Notify event-listeners.
Definition at line 246 of file GameOfLifeControls.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.getShapeSelectedEvent().
Referenced by org.bitstorm.gameoflife.GameOfLifeControls.GameOfLifeControls().
{
     GameOfLifeControlsEvent event = GameOfLifeControlsEvent.getShapeSelectedEvent( this, shapeName );
     for ( Enumeration e = listeners.elements(); e.hasMoreElements(); )
       ((GameOfLifeControlsListener) e.nextElement()).shapeSelected( event );
   }
void org.bitstorm.gameoflife.GameOfLifeControls.speedChanged (int speed)
Called when a new speed from the speed pull down is selected. Notify event-listeners.
Definition at line 226 of file GameOfLifeControls.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.getSpeedChangedEvent().
Referenced by org.bitstorm.gameoflife.GameOfLifeControls.GameOfLifeControls().
{
     GameOfLifeControlsEvent event = GameOfLifeControlsEvent.getSpeedChangedEvent( this, speed );
     for ( Enumeration e = listeners.elements(); e.hasMoreElements(); )
       ((GameOfLifeControlsListener) e.nextElement()).speedChanged( event );
   }
void org.bitstorm.gameoflife.GameOfLifeControls.start ()
Start-button is activated.
Definition at line 187 of file GameOfLifeControls.java.
Referenced by org.bitstorm.gameoflife.GameOfLife.start2().
                       {
     startstopButton.setLabel(stopLabelText);
     nextButton.disable();
     shapesChoice.disable();
   }
void org.bitstorm.gameoflife.GameOfLifeControls.startStopButtonClicked ()
Called when the start/stop-button is clicked. Notify event-listeners.
Definition at line 206 of file GameOfLifeControls.java.
Referenced by org.bitstorm.gameoflife.GameOfLifeControls.GameOfLifeControls().
{
     GameOfLifeControlsEvent event = new GameOfLifeControlsEvent( this );
     for ( Enumeration e = listeners.elements(); e.hasMoreElements(); )
       ((GameOfLifeControlsListener) e.nextElement()).startStopButtonClicked( event );
   }
void org.bitstorm.gameoflife.GameOfLifeControls.stop ()
Stop-button is activated.
Definition at line 196 of file GameOfLifeControls.java.
Referenced by org.bitstorm.gameoflife.GameOfLife.stop().
                      {
     startstopButton.setLabel(startLabelText);
     nextButton.enable();
     shapesChoice.enable();
   }
void org.bitstorm.gameoflife.GameOfLifeControls.zoomChanged (int zoom)
Called when a new zoom from the zoom pull down is selected. Notify event-listeners.
Definition at line 236 of file GameOfLifeControls.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.getZoomChangedEvent().
Referenced by org.bitstorm.gameoflife.GameOfLifeControls.GameOfLifeControls().
{
     GameOfLifeControlsEvent event = GameOfLifeControlsEvent.getZoomChangedEvent( this, zoom );
     for ( Enumeration e = listeners.elements(); e.hasMoreElements(); )
       ((GameOfLifeControlsListener) e.nextElement()).zoomChanged( event );
   }
Member Data Documentation
final String org.bitstorm.gameoflife.GameOfLifeControls.BIG = "Big" static
Definition at line 41 of file GameOfLifeControls.java.
final String org.bitstorm.gameoflife.GameOfLifeControls.FAST = "Fast" static
Definition at line 39 of file GameOfLifeControls.java.
Label org.bitstorm.gameoflife.GameOfLifeControls.genLabel private
Definition at line 33 of file GameOfLifeControls.java.
final String org.bitstorm.gameoflife.GameOfLifeControls.genLabelText = "Generations: " private
Definition at line 34 of file GameOfLifeControls.java.
final String org.bitstorm.gameoflife.GameOfLifeControls.HYPER = "Hyper" static
Definition at line 40 of file GameOfLifeControls.java.
Vector org.bitstorm.gameoflife.GameOfLifeControls.listeners private
Definition at line 49 of file GameOfLifeControls.java.
final String org.bitstorm.gameoflife.GameOfLifeControls.MEDIUM = "Medium" static
Definition at line 42 of file GameOfLifeControls.java.
Button org.bitstorm.gameoflife.GameOfLifeControls.nextButton private
Definition at line 48 of file GameOfLifeControls.java.
final String org.bitstorm.gameoflife.GameOfLifeControls.nextLabelText = "Next" private
Definition at line 35 of file GameOfLifeControls.java.
Choice org.bitstorm.gameoflife.GameOfLifeControls.shapesChoice private
Definition at line 50 of file GameOfLifeControls.java.
final int org.bitstorm.gameoflife.GameOfLifeControls.SIZE_BIG = 11 static
Definition at line 44 of file GameOfLifeControls.java.
final int org.bitstorm.gameoflife.GameOfLifeControls.SIZE_MEDIUM = 7 static
Definition at line 45 of file GameOfLifeControls.java.
final int org.bitstorm.gameoflife.GameOfLifeControls.SIZE_SMALL = 3 static
Definition at line 46 of file GameOfLifeControls.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
final String org.bitstorm.gameoflife.GameOfLifeControls.SLOW = "Slow" static
Definition at line 38 of file GameOfLifeControls.java.
final String org.bitstorm.gameoflife.GameOfLifeControls.SMALL = "Small" static
Definition at line 43 of file GameOfLifeControls.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
final String org.bitstorm.gameoflife.GameOfLifeControls.startLabelText = "Start" private
Definition at line 36 of file GameOfLifeControls.java.
Button org.bitstorm.gameoflife.GameOfLifeControls.startstopButton private
Definition at line 47 of file GameOfLifeControls.java.
final String org.bitstorm.gameoflife.GameOfLifeControls.stopLabelText = "Stop" private
Definition at line 37 of file GameOfLifeControls.java.
Choice org.bitstorm.gameoflife.GameOfLifeControls.zoomChoice private
Definition at line 51 of file GameOfLifeControls.java.
The documentation for this class was generated from the following file:
GameOfLifeControls.java