Game-of-Life-WSU-CEG4180: org.bitstorm.gameoflife.GameOfLifeControlsEvent Class Reference
org.bitstorm.gameoflife.GameOfLifeControlsEvent Class Reference
Public Member Functions
GameOfLifeControlsEvent (Object source)
int getSpeed ()
void setSpeed (int speed)
int getZoom ()
void setZoom (int zoom)
String getShapeName ()
void setShapeName (String shapeName)
Static Public Member Functions
static GameOfLifeControlsEvent getSpeedChangedEvent (Object source, int speed)
static GameOfLifeControlsEvent getZoomChangedEvent (Object source, int zoom)
static GameOfLifeControlsEvent getShapeSelectedEvent (Object source, String shapeName)
Private Attributes
int speed
int zoom
String shapeName
Detailed Description
Event class for GameOfLifeControls. Can pass speed, cellSize and shapeName. Objects from this class are generated by GameOfLifeControls
See also
GameOfLifeControls
Author
Edwin Martin
Definition at line 14 of file GameOfLifeControlsEvent.java.
Constructor & Destructor Documentation
org.bitstorm.gameoflife.GameOfLifeControlsEvent.GameOfLifeControlsEvent (Object source)
Construct a GameOfLifeControls.ControlsEvent
Parameters
source source of event
Definition at line 23 of file GameOfLifeControlsEvent.java.
Referenced by org.bitstorm.gameoflife.GameOfLifeControlsEvent.getShapeSelectedEvent(), org.bitstorm.gameoflife.GameOfLifeControlsEvent.getSpeedChangedEvent(), and org.bitstorm.gameoflife.GameOfLifeControlsEvent.getZoomChangedEvent().
{
     super(source, 0, null);
   }
Member Function Documentation
String org.bitstorm.gameoflife.GameOfLifeControlsEvent.getShapeName ()
Gets name of shape
Returns
name of selected shape
Definition at line 99 of file GameOfLifeControlsEvent.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.shapeName.
Referenced by org.bitstorm.gameoflife.GameOfLife.shapeSelected().
{
     return shapeName;
   }
static GameOfLifeControlsEvent org.bitstorm.gameoflife.GameOfLifeControlsEvent.getShapeSelectedEvent (Object source, String shapeName) static
Constructs a event due to the shape changed.
Parameters
source source of the event
shapeName name of selected shape
Returns
new event object
Definition at line 57 of file GameOfLifeControlsEvent.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.GameOfLifeControlsEvent().
Referenced by org.bitstorm.gameoflife.GameOfLifeControls.shapeSelected().
{
     GameOfLifeControlsEvent event = new GameOfLifeControlsEvent(source);
     event.setShapeName(shapeName);
     return event;
   }
int org.bitstorm.gameoflife.GameOfLifeControlsEvent.getSpeed ()
Gets speed of Game
Returns
speed (10 is fast, 1000 is slow)
Definition at line 67 of file GameOfLifeControlsEvent.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.speed.
Referenced by org.bitstorm.gameoflife.GameOfLife.speedChanged().
{
     return speed;
   }
static GameOfLifeControlsEvent org.bitstorm.gameoflife.GameOfLifeControlsEvent.getSpeedChangedEvent (Object source, int speed) static
Constructs a event due to the speed changed.
Parameters
source source of the event
speed new speed
Returns
new event object
Definition at line 33 of file GameOfLifeControlsEvent.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.GameOfLifeControlsEvent().
Referenced by org.bitstorm.gameoflife.GameOfLifeControls.speedChanged().
{
     GameOfLifeControlsEvent event = new GameOfLifeControlsEvent(source);
     event.setSpeed(speed);
     return event;
   }
int org.bitstorm.gameoflife.GameOfLifeControlsEvent.getZoom ()
Gets size of cell
Returns
speed (10 is big, 2 is small)
Definition at line 83 of file GameOfLifeControlsEvent.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.zoom.
Referenced by org.bitstorm.gameoflife.GameOfLife.zoomChanged().
{
     return zoom;
   }
static GameOfLifeControlsEvent org.bitstorm.gameoflife.GameOfLifeControlsEvent.getZoomChangedEvent (Object source, int zoom) static
Constructs a event due to the zoom changed.
Parameters
source source of the event
zoom new zoom (cell size in pixels)
Returns
new event object
Definition at line 45 of file GameOfLifeControlsEvent.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.GameOfLifeControlsEvent().
Referenced by org.bitstorm.gameoflife.GameOfLifeControls.zoomChanged().
{
     GameOfLifeControlsEvent event = new GameOfLifeControlsEvent(source);
     event.setZoom(zoom);
     return event;
   }
void org.bitstorm.gameoflife.GameOfLifeControlsEvent.setShapeName (String shapeName)
Sets name of shape
Parameters
shapeName name of shape
Definition at line 107 of file GameOfLifeControlsEvent.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.shapeName.
{
     this.shapeName = shapeName;
   }
void org.bitstorm.gameoflife.GameOfLifeControlsEvent.setSpeed (int speed)
Sets speed of Game
Parameters
speed (10 is fast, 1000 is slow)
Definition at line 75 of file GameOfLifeControlsEvent.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.speed.
{
     this.speed = speed;
   }
void org.bitstorm.gameoflife.GameOfLifeControlsEvent.setZoom (int zoom)
Sets zoom of Game
Parameters
zoom size of cell in pixels
Definition at line 91 of file GameOfLifeControlsEvent.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.zoom.
{
     this.zoom = zoom;
   }
Member Data Documentation
String org.bitstorm.gameoflife.GameOfLifeControlsEvent.shapeName private
Definition at line 17 of file GameOfLifeControlsEvent.java.
Referenced by org.bitstorm.gameoflife.GameOfLifeControlsEvent.getShapeName(), and org.bitstorm.gameoflife.GameOfLifeControlsEvent.setShapeName().
int org.bitstorm.gameoflife.GameOfLifeControlsEvent.speed private
Definition at line 15 of file GameOfLifeControlsEvent.java.
Referenced by org.bitstorm.gameoflife.GameOfLifeControlsEvent.getSpeed(), and org.bitstorm.gameoflife.GameOfLifeControlsEvent.setSpeed().
int org.bitstorm.gameoflife.GameOfLifeControlsEvent.zoom private
Definition at line 16 of file GameOfLifeControlsEvent.java.
Referenced by org.bitstorm.gameoflife.GameOfLifeControlsEvent.getZoom(), and org.bitstorm.gameoflife.GameOfLifeControlsEvent.setZoom().
The documentation for this class was generated from the following file:
GameOfLifeControlsEvent.java