Game-of-Life-WSU-CEG4180: org.bitstorm.gameoflife.GameOfLifeGrid Class Reference
org.bitstorm.gameoflife.GameOfLifeGrid Class Reference
Public Member Functions
GameOfLifeGrid (int cellCols, int cellRows)
synchronized void clear ()
synchronized void next ()
synchronized void addNeighbour (int col, int row)
Enumeration getEnum ()
synchronized boolean getCell (int col, int row)
synchronized void setCell (int col, int row, boolean c)
int getGenerations ()
Dimension getDimension ()
synchronized void resize (int cellColsNew, int cellRowsNew)
Private Attributes
int cellRows
int cellCols
int generations
Hashtable currentShape
Hashtable nextShape
Cell[][] grid
Static Private Attributes
static Shape[] shapes
Detailed Description
Contains the cellgrid, the current shape and the Game Of Life algorithm that changes it.
Author
Edwin Martin
Definition at line 19 of file GameOfLifeGrid.java.
Constructor & Destructor Documentation
org.bitstorm.gameoflife.GameOfLifeGrid.GameOfLifeGrid (int cellCols, int cellRows)
Contructs a GameOfLifeGrid.
Parameters
cellCols number of columns
cellRows number of rows
Definition at line 41 of file GameOfLifeGrid.java.
References org.bitstorm.gameoflife.GameOfLifeGrid.cellCols, and org.bitstorm.gameoflife.GameOfLifeGrid.cellRows.
{
     this.cellCols = cellCols;
     this.cellRows = cellRows;
     currentShape = new Hashtable();
     nextShape = new Hashtable();
     grid = new Cell[cellCols][cellRows];
     for ( int c=0; c<cellCols; c++)
       for ( int r=0; r<cellRows; r++ )
         grid[c][r] = new Cell( c, r );
   }
Member Function Documentation
synchronized void org.bitstorm.gameoflife.GameOfLifeGrid.addNeighbour (int col, int row)
Adds a new neighbour to a cell.
Parameters
col Cell-column
row Cell-row
Definition at line 125 of file GameOfLifeGrid.java.
References org.bitstorm.gameoflife.Cell.neighbour.
Referenced by org.bitstorm.gameoflife.GameOfLifeGrid.next().
{
     try {
       Cell cell = (Cell)nextShape.get( grid[col][row] );
       if ( cell == null ) {
         // Cell is not in hashtable, then add it
         Cell c = grid[col][row];
         c.neighbour = 1;
         nextShape.put(c, c);
       } else {
         // Else, increments neighbour count
         cell.neighbour++;
       }
     } catch (ArrayIndexOutOfBoundsException e) {
       // ignore
     }
   }
synchronized void org.bitstorm.gameoflife.GameOfLifeGrid.clear ()
Clears grid.
Implements org.bitstorm.gameoflife.CellGrid.
Definition at line 56 of file GameOfLifeGrid.java.
Referenced by org.bitstorm.gameoflife.GameOfLife.init(), and org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.makeShape().
{
     generations = 0;
     currentShape.clear();
     nextShape.clear();
   }
synchronized boolean org.bitstorm.gameoflife.GameOfLifeGrid.getCell (int col, int row)
Get value of cell.
Parameters
col x-coordinate of cell
row y-coordinate of cell
Returns
value of cell
Implements org.bitstorm.gameoflife.CellGrid.
Definition at line 156 of file GameOfLifeGrid.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.saveShape().
{
     try {
       return currentShape.containsKey(grid[col][row]);
     } catch (ArrayIndexOutOfBoundsException e) {
       // ignore
     }
     return false;
   }
Dimension org.bitstorm.gameoflife.GameOfLifeGrid.getDimension ()
Get dimension of grid.
Returns
dimension of grid
Implements org.bitstorm.gameoflife.CellGrid.
Definition at line 196 of file GameOfLifeGrid.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.saveShape(), and org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
{
     return new Dimension( cellCols, cellRows );
   }
Enumeration org.bitstorm.gameoflife.GameOfLifeGrid.getEnum ()
Get enumeration of Cell's
See also
org.bitstorm.gameoflife.CellGrid::getEnum()
Implements org.bitstorm.gameoflife.CellGrid.
Definition at line 146 of file GameOfLifeGrid.java.
{
     return currentShape.keys();
   }
int org.bitstorm.gameoflife.GameOfLifeGrid.getGenerations ()
Get number of generations.
Returns
number of generations
Definition at line 188 of file GameOfLifeGrid.java.
References org.bitstorm.gameoflife.GameOfLifeGrid.generations.
Referenced by org.bitstorm.gameoflife.GameOfLife.showGenerations().
{
     return generations;
   }
synchronized void org.bitstorm.gameoflife.GameOfLifeGrid.next ()
Create next generation of shape.
Definition at line 65 of file GameOfLifeGrid.java.
References org.bitstorm.gameoflife.GameOfLifeGrid.addNeighbour(), org.bitstorm.gameoflife.Cell.col, org.bitstorm.gameoflife.Cell.neighbour, org.bitstorm.gameoflife.Cell.row, and org.bitstorm.gameoflife.GameOfLifeGrid.setCell().
Referenced by org.bitstorm.gameoflife.GameOfLife.nextGeneration().
{
     Cell cell;
     int col, row;
     int neighbours;
     Enumeration enum;
     generations++;
     nextShape.clear();
     // Reset cells
     enum = currentShape.keys();
     while ( enum.hasMoreElements() ) {
       cell = (Cell) enum.nextElement();
       cell.neighbour = 0;
     }
     // Add neighbours
     // You can't walk through an hashtable and also add elements. Took me a couple of ours to figure out. Argh!
     // That's why we have a hashNew hashtable.
     enum = currentShape.keys();
     while ( enum.hasMoreElements() ) {
       cell = (Cell) enum.nextElement();
       col = cell.col;
       row = cell.row;
       addNeighbour( col-1, row-1 );
       addNeighbour( col, row-1 );
       addNeighbour( col+1, row-1 );
       addNeighbour( col-1, row );
       addNeighbour( col+1, row );
       addNeighbour( col-1, row+1 );
       addNeighbour( col, row+1 );
       addNeighbour( col+1, row+1 );
     }
     // Bury the dead
     // We are walking through an enum from we are also removing elements. Can be tricky.
     enum = currentShape.keys();
     while ( enum.hasMoreElements() ) {
       cell = (Cell) enum.nextElement();
       // Here is the Game Of Life rule (1):
       if ( cell.neighbour != 3 && cell.neighbour != 2 ) {
         currentShape.remove( cell );
       }
     }
     // Bring out the new borns
     enum = nextShape.keys();
     while ( enum.hasMoreElements() ) {
       cell = (Cell) enum.nextElement();
       // Here is the Game Of Life rule (2):
       if ( cell.neighbour == 3 ) {
         setCell( cell.col, cell.row, true );
       }
     }
   }
synchronized void org.bitstorm.gameoflife.GameOfLifeGrid.resize (int cellColsNew, int cellRowsNew)
Resize grid. Reuse existing cells.
See also
org.bitstorm.gameoflife.CellGrid::resize(int, int)
Implements org.bitstorm.gameoflife.CellGrid.
Definition at line 204 of file GameOfLifeGrid.java.
References org.bitstorm.gameoflife.GameOfLifeGrid.cellCols, org.bitstorm.gameoflife.GameOfLifeGrid.cellRows, org.bitstorm.gameoflife.Cell.col, and org.bitstorm.gameoflife.Cell.row.
{
     if ( cellCols==cellColsNew && cellRows==cellRowsNew )
       return; // Not really a resize
     // Create a new grid, reusing existing Cell's
     Cell[][] gridNew = new Cell[cellColsNew][cellRowsNew];
     for ( int c=0; c<cellColsNew; c++)
       for ( int r=0; r<cellRowsNew; r++ )
         if ( c < cellCols && r < cellRows )
           gridNew[c][r] = grid[c][r];
         else
           gridNew[c][r] = new Cell( c, r );
     // Copy existing shape to center of new shape
     int colOffset = (cellColsNew-cellCols)/2;
     int rowOffset = (cellRowsNew-cellRows)/2;
     Cell cell;
     Enumeration enum;
     nextShape.clear();
     enum = currentShape.keys();
     while ( enum.hasMoreElements() ) {
       cell = (Cell) enum.nextElement();
       int colNew = cell.col + colOffset;
       int rowNew = cell.row + rowOffset;
       try {
         nextShape.put( gridNew[colNew][rowNew], gridNew[colNew][rowNew] );
       } catch ( ArrayIndexOutOfBoundsException e ) {
         // ignore
       }
     }
     // Copy new grid and hashtable to working grid/hashtable
     grid = gridNew;
     currentShape.clear();
     enum = nextShape.keys();
     while ( enum.hasMoreElements() ) {
       cell = (Cell) enum.nextElement();
       currentShape.put( cell, cell );
     }
     cellCols = cellColsNew;
     cellRows = cellRowsNew;
   }
synchronized void org.bitstorm.gameoflife.GameOfLifeGrid.setCell (int col, int row, boolean c)
Set value of cell.
Parameters
col x-coordinate of cell
row y-coordinate of cell
c value of cell
Implements org.bitstorm.gameoflife.CellGrid.
Definition at line 171 of file GameOfLifeGrid.java.
Referenced by org.bitstorm.gameoflife.GameOfLifeGrid.next().
{
     try {
       Cell cell = grid[col][row];
       if ( c ) {
         currentShape.put(cell, cell);
       } else {
         currentShape.remove(cell);
       }
     } catch (ArrayIndexOutOfBoundsException e) {
       // ignore
     }
   }
Member Data Documentation
int org.bitstorm.gameoflife.GameOfLifeGrid.cellCols private
Definition at line 21 of file GameOfLifeGrid.java.
Referenced by org.bitstorm.gameoflife.GameOfLifeGrid.GameOfLifeGrid(), and org.bitstorm.gameoflife.GameOfLifeGrid.resize().
int org.bitstorm.gameoflife.GameOfLifeGrid.cellRows private
Definition at line 20 of file GameOfLifeGrid.java.
Referenced by org.bitstorm.gameoflife.GameOfLifeGrid.GameOfLifeGrid(), and org.bitstorm.gameoflife.GameOfLifeGrid.resize().
Hashtable org.bitstorm.gameoflife.GameOfLifeGrid.currentShape private
Contains the current, living shape. It's implemented as a hashtable. Tests showed this is 70% faster than Vector.
Definition at line 28 of file GameOfLifeGrid.java.
int org.bitstorm.gameoflife.GameOfLifeGrid.generations private
Definition at line 22 of file GameOfLifeGrid.java.
Referenced by org.bitstorm.gameoflife.GameOfLifeGrid.getGenerations().
Cell [][] org.bitstorm.gameoflife.GameOfLifeGrid.grid private
Every cell on the grid is a Cell object. This object can become quite large.
Definition at line 33 of file GameOfLifeGrid.java.
Hashtable org.bitstorm.gameoflife.GameOfLifeGrid.nextShape private
Definition at line 29 of file GameOfLifeGrid.java.
Shape [] org.bitstorm.gameoflife.GameOfLifeGrid.shapes static private
Definition at line 23 of file GameOfLifeGrid.java.
The documentation for this class was generated from the following file:
GameOfLifeGrid.java