Game-of-Life-WSU-CEG4180: org.bitstorm.util.TextFileDialog Class Reference
org.bitstorm.util.TextFileDialog Class Reference
Public Member Functions
TextFileDialog (Frame parent, String title, String filename, int posX, int posY)
void processEvent (AWTEvent e)
Private Member Functions
void close ()
Detailed Description
Shows a text file in a dialog box. It has a vertical scrollbar and a close button.
Author
Edwin Martin
Definition at line 26 of file TextFileDialog.java.
Constructor & Destructor Documentation
org.bitstorm.util.TextFileDialog.TextFileDialog (Frame parent, String title, String filename, int posX, int posY)
Constructs a TextFileDialog.
Parameters
parent parent frame
title window title
filename filename to show (from jar-file)
Definition at line 33 of file TextFileDialog.java.
References org.bitstorm.util.TextFileDialog.close(), and org.bitstorm.util.EasyFile.readText().
{
     super( parent, title );
     String manualText;
     Button okButton = new Button(" Close ");
     okButton.addActionListener(
       new ActionListener() {
         public void actionPerformed(ActionEvent e) {
           close();
         }
       }
     );
     EasyFile file = new EasyFile( this.getClass().getResourceAsStream( filename ) );
     try {
       manualText = file.readText();
     } catch (IOException e) {
       manualText = "";
     }
     TextArea manualTextArea = new TextArea( manualText, 20, 50, TextArea.SCROLLBARS_VERTICAL_ONLY );
     manualTextArea.setBackground( Color.white );  // improve readability
     manualTextArea.setForeground( Color.black );  // we don't want white text on a white background
     manualTextArea.setEditable(false);
     Panel buttonPanel = new Panel();
     buttonPanel.setLayout( new FlowLayout( FlowLayout.CENTER ) );
     buttonPanel.add( okButton );
     this.add( "Center", manualTextArea );
     this.add( "South", buttonPanel );
     this.pack();
     this.enableEvents(Event.WINDOW_DESTROY);
     this.setLocation( posX, posY );
     this.show();
   }
Member Function Documentation
void org.bitstorm.util.TextFileDialog.close () private
Close dialog box.
Definition at line 72 of file TextFileDialog.java.
Referenced by org.bitstorm.util.TextFileDialog.processEvent(), and org.bitstorm.util.TextFileDialog.TextFileDialog().
{
     this.hide();
     this.dispose();
   }
void org.bitstorm.util.TextFileDialog.processEvent (AWTEvent e)
Handle close window button.
See also
java.awt.Component::processEvent(java.awt.AWTEvent)
Definition at line 81 of file TextFileDialog.java.
References org.bitstorm.util.TextFileDialog.close().
{
     if ( e.getID() == Event.WINDOW_DESTROY )
       close();
   }
The documentation for this class was generated from the following file:
TextFileDialog.java