Game-of-Life-WSU-CEG4180: org.bitstorm.gameoflife.GameOfLife Class Reference
org.bitstorm.gameoflife.GameOfLife Class Reference
Public Member Functions
void init ()
synchronized void start2 ()
void stop ()
synchronized void run ()
boolean isRunning ()
void nextGeneration ()
void setShape (Shape shape)
void reset ()
String getAppletInfo ()
void setSpeed (int fps)
void setCellSize (int p)
int getCellSize ()
void alert (String s)
void startStopButtonClicked (GameOfLifeControlsEvent e)
void nextButtonClicked (GameOfLifeControlsEvent e)
void speedChanged (GameOfLifeControlsEvent e)
void zoomChanged (GameOfLifeControlsEvent e)
void shapeSelected (GameOfLifeControlsEvent e)
Protected Member Functions
void getParams ()
int getParamInteger (String name, int defaultParam)
Protected Attributes
CellGridCanvas gameOfLifeCanvas
GameOfLifeGrid gameOfLifeGrid
int cellSize
int cellCols
int cellRows
int genTime
GameOfLifeControls controls
Static Protected Attributes
static Thread gameThread = null
Private Member Functions
void showGenerations ()
Detailed Description
The Game Of Life Applet. This is the heart of the program. It initializes everything en put it together.
Author
Edwin Martin
Definition at line 29 of file GameOfLife.java.
Member Function Documentation
void org.bitstorm.gameoflife.GameOfLife.alert (String s)
Shows an alert
Parameters
s text to show
Definition at line 239 of file GameOfLife.java.
Referenced by org.bitstorm.gameoflife.GameOfLife.setShape().
{
     showStatus( s );
   }
String org.bitstorm.gameoflife.GameOfLife.getAppletInfo ()
See also
java.applet.Applet::getAppletInfo()
Definition at line 199 of file GameOfLife.java.
{
     return "Game Of Life v. 1.5\nCopyright 1996-2004 Edwin Martin";
   }
int org.bitstorm.gameoflife.GameOfLife.getCellSize ()
Gets cell size.
Returns
size of cell
Definition at line 231 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLife.cellSize.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
{
     return cellSize;
   }
int org.bitstorm.gameoflife.GameOfLife.getParamInteger (String name, int defaultParam) protected
Read applet parameter (int) or, when unavailable, get default value.
Parameters
name name of parameter
defaultParam default when parameter is unavailable
Returns
value of parameter
Definition at line 107 of file GameOfLife.java.
Referenced by org.bitstorm.gameoflife.GameOfLife.getParams().
{
     String param;
     int paramInt;
     param = getParameter( name );
     if ( param == null )
       paramInt = defaultParam;
     else
       paramInt = Integer.valueOf(param).intValue();
     return paramInt;
   }
void org.bitstorm.gameoflife.GameOfLife.getParams () protected
Get params (cellSize, cellCols, cellRows, genTime) from applet-tag
Definition at line 94 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLife.getParamInteger().
Referenced by org.bitstorm.gameoflife.GameOfLife.init(), and org.bitstorm.gameoflife.StandaloneGameOfLife.init().
{
     cellSize = getParamInteger( "cellsize", 11 );
     cellCols = getParamInteger( "cellcols", 50 );
     cellRows = getParamInteger( "cellrows", 30 );
     genTime  = getParamInteger( "gentime", 1000 );
   }
void org.bitstorm.gameoflife.GameOfLife.init ()
Initialize UI.
See also
java.applet.Applet::init()
Definition at line 43 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLifeControls.addGameOfLifeControlsListener(), org.bitstorm.gameoflife.GameOfLifeGrid.clear(), org.bitstorm.gameoflife.GameOfLife.getParams(), org.bitstorm.gameoflife.ShapeCollection.getShapeByName(), and org.bitstorm.gameoflife.GameOfLife.setShape().
                      {
     getParams();
     // set background colour
     setBackground(new Color(0x999999));
     // create gameOfLifeGrid
     gameOfLifeGrid = new GameOfLifeGrid(cellCols, cellRows);
     gameOfLifeGrid.clear();
     // create GameOfLifeCanvas
     gameOfLifeCanvas = new CellGridCanvas(gameOfLifeGrid, cellSize);
     // create GameOfLifeControls
     controls = new GameOfLifeControls();
     controls.addGameOfLifeControlsListener( this );
     // put it all together
         GridBagLayout gridbag = new GridBagLayout();
         setLayout(gridbag);
         GridBagConstraints canvasContraints = new GridBagConstraints();
         canvasContraints.fill = GridBagConstraints.BOTH;
         canvasContraints.gridx = GridBagConstraints.REMAINDER;
         canvasContraints.gridy = 0;
         canvasContraints.weightx = 1;
         canvasContraints.weighty = 1;
         canvasContraints.anchor = GridBagConstraints.CENTER;
         gridbag.setConstraints(gameOfLifeCanvas, canvasContraints);
         add(gameOfLifeCanvas);
         GridBagConstraints controlsContraints = new GridBagConstraints();
         canvasContraints.gridy = 1;
         canvasContraints.gridx = 0;
         controlsContraints.gridx = GridBagConstraints.REMAINDER;
         gridbag.setConstraints(controls, controlsContraints);
         add(controls);
         try {
       // Start with a shape (My girlfriend clicked "Start" on a blank screen and wondered why nothing happened).
       setShape( ShapeCollection.getShapeByName( "Glider" ) );
     } catch (ShapeException e) {
       // Ignore. Not going to happen.
     }
     setVisible(true);
     validate();
   }
boolean org.bitstorm.gameoflife.GameOfLife.isRunning ()
Is the applet running?
Returns
true: applet is running
Definition at line 157 of file GameOfLife.java.
Referenced by org.bitstorm.gameoflife.GameOfLife.startStopButtonClicked().
{
     return gameThread != null;
   }
void org.bitstorm.gameoflife.GameOfLife.nextButtonClicked (GameOfLifeControlsEvent e)
Callback from GameOfLifeControlsListener
See also
org.bitstorm.gameoflife.GameOfLifeControlsListener::nextButtonClicked(org.bitstorm.gameoflife.GameOfLifeControlsEvent)
Implements org.bitstorm.gameoflife.GameOfLifeControlsListener.
Definition at line 257 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLife.nextGeneration().
{
     nextGeneration();
   }
void org.bitstorm.gameoflife.GameOfLife.nextGeneration ()
Go to the next generation.
Definition at line 164 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLifeGrid.next(), and org.bitstorm.gameoflife.GameOfLife.showGenerations().
Referenced by org.bitstorm.gameoflife.GameOfLife.nextButtonClicked(), and org.bitstorm.gameoflife.GameOfLife.run().
{
     gameOfLifeGrid.next();
     gameOfLifeCanvas.repaint();
     showGenerations();
   }
void org.bitstorm.gameoflife.GameOfLife.reset ()
Resets applet (after loading new shape)
Definition at line 189 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLife.showGenerations(), and org.bitstorm.gameoflife.GameOfLife.stop().
Referenced by org.bitstorm.gameoflife.AppletFrame.AppletFrame(), org.bitstorm.gameoflife.StandaloneGameOfLife.MyDropListener.drop(), org.bitstorm.gameoflife.StandaloneGameOfLife.readShape(), and org.bitstorm.gameoflife.GameOfLife.setShape().
                       {
     stop(); // might otherwise confuse user
     gameOfLifeCanvas.repaint();
     showGenerations();
     showStatus( "" );
   }
synchronized void org.bitstorm.gameoflife.GameOfLife.run ()
See also
java.lang.Runnable::run()
Definition at line 142 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLife.nextGeneration().
{
     while (gameThread != null) {
       nextGeneration();
       try {
         Thread.sleep(genTime);
       } catch (InterruptedException e) {
         e.printStackTrace();
       }
     }
   }
void org.bitstorm.gameoflife.GameOfLife.setCellSize (int p)
Sets cell size.
Parameters
p size of cell in pixels
Definition at line 222 of file GameOfLife.java.
References org.bitstorm.gameoflife.CellGridCanvas.setCellSize().
Referenced by org.bitstorm.gameoflife.GameOfLife.zoomChanged().
{
     cellSize = p;
     gameOfLifeCanvas.setCellSize( cellSize );
   }
void org.bitstorm.gameoflife.GameOfLife.setShape (Shape shape)
Set the new shape
Parameters
shape name of shape
Definition at line 174 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLife.alert(), org.bitstorm.gameoflife.GameOfLife.reset(), and org.bitstorm.gameoflife.CellGridCanvas.setShape().
Referenced by org.bitstorm.gameoflife.GameOfLife.init(), org.bitstorm.gameoflife.StandaloneGameOfLife.readShape(), and org.bitstorm.gameoflife.GameOfLife.shapeSelected().
{
     if ( shape == null )
       return;
     try {
       gameOfLifeCanvas.setShape( shape );
       reset();
     } catch (ShapeException e) {
       alert( e.getMessage() );
     }
   }
void org.bitstorm.gameoflife.GameOfLife.setSpeed (int fps)
Set speed of new generations.
Parameters
fps generations per second
Definition at line 214 of file GameOfLife.java.
Referenced by org.bitstorm.gameoflife.GameOfLife.speedChanged().
{
     genTime = fps;
   }
void org.bitstorm.gameoflife.GameOfLife.shapeSelected (GameOfLifeControlsEvent e)
Callback from GameOfLifeControlsListener
See also
org.bitstorm.gameoflife.GameOfLifeControlsListener::shapeSelected(org.bitstorm.gameoflife.GameOfLifeControlsEvent)
Implements org.bitstorm.gameoflife.GameOfLifeControlsListener.
Definition at line 278 of file GameOfLife.java.
References org.bitstorm.gameoflife.ShapeCollection.getShapeByName(), org.bitstorm.gameoflife.GameOfLifeControlsEvent.getShapeName(), and org.bitstorm.gameoflife.GameOfLife.setShape().
{
     String shapeName = (String) e.getShapeName();
     Shape shape;
     try {
       shape = ShapeCollection.getShapeByName( shapeName );
       setShape( shape );
     } catch (ShapeException e1) {
       // Ignore. Not going to happen.
     }
   }
void org.bitstorm.gameoflife.GameOfLife.showGenerations () private
Show number of generations.
Definition at line 206 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLifeGrid.getGenerations(), and org.bitstorm.gameoflife.GameOfLifeControls.setGeneration().
Referenced by org.bitstorm.gameoflife.GameOfLife.nextGeneration(), and org.bitstorm.gameoflife.GameOfLife.reset().
{
     controls.setGeneration( gameOfLifeGrid.getGenerations() );
   }
void org.bitstorm.gameoflife.GameOfLife.speedChanged (GameOfLifeControlsEvent e)
Callback from GameOfLifeControlsListener
See also
org.bitstorm.gameoflife.GameOfLifeControlsListener::speedChanged(org.bitstorm.gameoflife.GameOfLifeControlsEvent)
Implements org.bitstorm.gameoflife.GameOfLifeControlsListener.
Definition at line 264 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.getSpeed(), and org.bitstorm.gameoflife.GameOfLife.setSpeed().
{
     setSpeed( e.getSpeed() );
   }
synchronized void org.bitstorm.gameoflife.GameOfLife.start2 ()
Starts creating new generations. No start() to prevent starting immediately.
Definition at line 123 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLifeControls.start().
Referenced by org.bitstorm.gameoflife.GameOfLife.startStopButtonClicked().
{
     controls.start();
     if (gameThread == null) {
       gameThread = new Thread(this);
       gameThread.start();
     }
   }
void org.bitstorm.gameoflife.GameOfLife.startStopButtonClicked (GameOfLifeControlsEvent e)
Callback from GameOfLifeControlsListener
See also
org.bitstorm.gameoflife.GameOfLifeControlsListener::startStopButtonClicked(org.bitstorm.gameoflife.GameOfLifeControlsEvent)
Implements org.bitstorm.gameoflife.GameOfLifeControlsListener.
Definition at line 246 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLife.isRunning(), org.bitstorm.gameoflife.GameOfLife.start2(), and org.bitstorm.gameoflife.GameOfLife.stop().
{
     if ( isRunning() ) {
       stop();
     } else {
       start2();
     }
   }
void org.bitstorm.gameoflife.GameOfLife.stop ()
See also
java.applet.Applet::stop()
Definition at line 134 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLifeControls.stop().
Referenced by org.bitstorm.gameoflife.GameOfLife.reset(), and org.bitstorm.gameoflife.GameOfLife.startStopButtonClicked().
                      {
     controls.stop();
     gameThread = null;
   }
void org.bitstorm.gameoflife.GameOfLife.zoomChanged (GameOfLifeControlsEvent e)
Callback from GameOfLifeControlsListener
See also
org.bitstorm.gameoflife.GameOfLifeControlsListener::speedChanged(org.bitstorm.gameoflife.GameOfLifeControlsEvent)
Implements org.bitstorm.gameoflife.GameOfLifeControlsListener.
Definition at line 271 of file GameOfLife.java.
References org.bitstorm.gameoflife.GameOfLifeControlsEvent.getZoom(), and org.bitstorm.gameoflife.GameOfLife.setCellSize().
{
     setCellSize( e.getZoom() );
   }
Member Data Documentation
int org.bitstorm.gameoflife.GameOfLife.cellCols protected
Definition at line 33 of file GameOfLife.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.init().
int org.bitstorm.gameoflife.GameOfLife.cellRows protected
Definition at line 34 of file GameOfLife.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.init().
int org.bitstorm.gameoflife.GameOfLife.cellSize protected
Definition at line 32 of file GameOfLife.java.
Referenced by org.bitstorm.gameoflife.GameOfLife.getCellSize(), org.bitstorm.gameoflife.StandaloneGameOfLife.init(), and org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
GameOfLifeControls org.bitstorm.gameoflife.GameOfLife.controls protected
Definition at line 36 of file GameOfLife.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.init(), and org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
CellGridCanvas org.bitstorm.gameoflife.GameOfLife.gameOfLifeCanvas protected
Definition at line 30 of file GameOfLife.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.init(), and org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
GameOfLifeGrid org.bitstorm.gameoflife.GameOfLife.gameOfLifeGrid protected
Definition at line 31 of file GameOfLife.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.init().
Thread org.bitstorm.gameoflife.GameOfLife.gameThread = null static protected
Definition at line 37 of file GameOfLife.java.
int org.bitstorm.gameoflife.GameOfLife.genTime protected
Definition at line 35 of file GameOfLife.java.
The documentation for this class was generated from the following file:
GameOfLife.java