Game-of-Life-WSU-CEG4180: org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO Class Reference
org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO Class Reference
Public Member Functions
GameOfLifeGridIO (GameOfLifeGrid grid)
void openShape ()
void openShape (String filename)
void openShape (URL url)
void openShape (EasyFile file) throws IOException
void setShape (Shape shape)
Shape makeShape (String name, String text)
void saveShape ()
Public Attributes
final String FILE_EXTENSION = ".cells"
Private Attributes
GameOfLifeGrid grid
String filename
Detailed Description
File open and save operations for GameOfLifeGrid.
Definition at line 254 of file StandaloneGameOfLife.java.
Constructor & Destructor Documentation
org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.GameOfLifeGridIO (GameOfLifeGrid grid)
Constructor.
Parameters
grid grid to read/write files from/to
Definition at line 263 of file StandaloneGameOfLife.java.
References org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.grid.
{
       this.grid = grid;
     }
Member Function Documentation
Shape org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.makeShape (String name, String text)
"Draw" the shape on the grid. (Okay, it's not really drawing). The lines of text represent the cells of the shape.
Parameters
name name of shape
text lines of text
Definition at line 386 of file StandaloneGameOfLife.java.
References org.bitstorm.gameoflife.GameOfLifeGrid.clear().
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.openShape().
{
       int col = 0;
       int row = 0;
       boolean cell;
       // Cope with different line endings ("\r\n", "\r", "\n")
       int[][] cellArray;
       Vector cells = new Vector();
       if ( text.length() == 0 )
         return null;
       grid.clear();
       Enumeration enm = new LineEnumerator( text );
       while ( enm.hasMoreElements() ) {
         String line = (String) enm.nextElement();
         if ( line.startsWith("#") || line.startsWith("!") )
           continue;
         char[] ca = line.toCharArray();
         for ( col=0; col < ca.length; col++ ) {
           switch( ca[col] ) {
             case '*':
             case 'O':
             case 'o':
             case 'X':
             case 'x':
             case '1':
               cell = true;
               break;
             default:
               cell = false;
               break;
           }
           if ( cell )
             cells.addElement(new int[] {col, row});
         }
         row++;
       }
       cellArray = new int[cells.size()][];
       for ( int i=0; i<cells.size(); i++ )
         cellArray[i] = (int[]) cells.get(i);
       return new Shape( name, cellArray );
     }
void org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.openShape ()
Load shape from disk
Definition at line 270 of file StandaloneGameOfLife.java.
Referenced by org.bitstorm.gameoflife.AppletFrame.AppletFrame(), org.bitstorm.gameoflife.StandaloneGameOfLife.MyDropListener.drop(), org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.openShape(), and org.bitstorm.gameoflife.StandaloneGameOfLife.readShape().
{
       openShape( (String)null );
     }
void org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.openShape (String filename)
Load shape from disk
Parameters
filename filename to load shape from, or null when no filename given.
Definition at line 278 of file StandaloneGameOfLife.java.
References org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.openShape().
{
       int col = 0;
       int row = 0;
       boolean cell;
       // Cope with different line endings ("\r\n", "\r", "\n")
       boolean nextLine = false;
       EasyFile file;
       try {
         if ( filename != null ) {
           file = new EasyFile( filename );
         } else {
           file = new EasyFile( appletFrame, "Open Game of Life file" );
         }
         openShape( file );
       } catch (FileNotFoundException e) {
         new AlertBox( appletFrame, "File not found", "Couldn't open this file.\n"+e.getMessage());
       } catch (IOException e) {
         new AlertBox( appletFrame, "File read error", "Couldn't read this file.\n"+e.getMessage());
       }
     }
void org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.openShape (URL url)
Open shape from URL.
Parameters
url URL pointing to GameOfLife-file
Definition at line 303 of file StandaloneGameOfLife.java.
References org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.openShape().
{
       int col = 0;
       int row = 0;
       boolean cell;
       // Cope with different line endings ("\r\n", "\r", "\n")
       boolean nextLine = false;
       EasyFile file;
       String text;
       try {
         if ( url != null ) {
           file = new EasyFile( url );
           openShape( file );
         }
       } catch (FileNotFoundException e) {
         new AlertBox( appletFrame, "URL not found", "Couldn't open this URL.\n"+e.getMessage());
       } catch (IOException e) {
         new AlertBox( appletFrame, "URL read error", "Couldn't read this URL.\n"+e.getMessage());
       }
     }
void org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.openShape (EasyFile file) throws IOException
Use EasyFile object to read GameOfLife-file from.
Parameters
file EasyFile-object
Exceptions
IOException
See also
org.bitstorm.util.EasyFile
Definition at line 329 of file StandaloneGameOfLife.java.
References org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.makeShape(), and org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape().
{
       Shape shape = makeShape( file.getFileName(), file.readText() );
       setShape( shape );
     }
void org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.saveShape ()
Write shape to disk.
Definition at line 435 of file StandaloneGameOfLife.java.
References org.bitstorm.gameoflife.GameOfLifeGrid.getCell(), org.bitstorm.gameoflife.GameOfLifeGrid.getDimension(), org.bitstorm.util.EasyFile.setFileExtension(), org.bitstorm.util.EasyFile.setFileName(), and org.bitstorm.util.EasyFile.writeText().
Referenced by org.bitstorm.gameoflife.AppletFrame.AppletFrame().
{
       int colEnd = 0;
       int rowEnd = 0;
       Dimension dim = grid.getDimension();
       int colStart = dim.width;
       int rowStart = dim.height;
       String lineSeparator = System.getProperty( "line.separator" );
       StringBuffer text = new StringBuffer("!Generator: Game of Life (http://www.bitstorm.org/gameoflife/)"+lineSeparator+"!Variation: 23/3"+lineSeparator+"!"+lineSeparator);
       for ( int row = 0; row < dim.height; row++ ) {
         for ( int col = 0; col < dim.width; col++ ) {
           if ( grid.getCell( col, row ) ) {
             if ( row < rowStart )
               rowStart = row;
             if ( col < colStart )
               colStart = col;
             if ( row > rowEnd )
               rowEnd = row;
             if ( col > colEnd )
               colEnd = col;
           }
         }
       }
       for ( int row = rowStart; row <= rowEnd; row++ ) {
         for ( int col = colStart; col <= colEnd; col++ ) {
           text.append( grid.getCell( col, row ) ? 'O' : '-' );
         }
         text.append( lineSeparator );
       }
       EasyFile file;
       try {
         file = new EasyFile( appletFrame, "Save Game of Life file" );
         file.setFileName( filename );
         file.setFileExtension( FILE_EXTENSION );
         file.writeText( text.toString() );
       } catch (FileNotFoundException e) {
         new AlertBox( appletFrame, "File error", "Couldn't open this file.\n"+e.getMessage());
       } catch (IOException e) {
         new AlertBox( appletFrame, "File error", "Couldn't write to this file.\n"+e.getMessage());
       }
     }
void org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.setShape (Shape shape)
Set a shape and optionally resizes window.
Parameters
shape Shape to set
Definition at line 338 of file StandaloneGameOfLife.java.
References org.bitstorm.gameoflife.GameOfLife.cellSize, org.bitstorm.gameoflife.GameOfLife.controls, org.bitstorm.gameoflife.GameOfLife.gameOfLifeCanvas, org.bitstorm.gameoflife.GameOfLife.getCellSize(), org.bitstorm.gameoflife.Shape.getDimension(), org.bitstorm.gameoflife.GameOfLifeGrid.getDimension(), org.bitstorm.gameoflife.CellGridCanvas.setAfterWindowResize(), org.bitstorm.gameoflife.CellGridCanvas.setShape(), org.bitstorm.gameoflife.GameOfLifeControls.setZoom(), org.bitstorm.gameoflife.GameOfLifeControls.SIZE_SMALL, and org.bitstorm.gameoflife.GameOfLifeControls.SMALL.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.openShape().
{
       int width, height;
       Dimension shapeDim = shape.getDimension();
       Dimension gridDim = grid.getDimension();
       if ( shapeDim.width > gridDim.width || shapeDim.height > gridDim.height ) {
         // Window has to be made larger
         Toolkit toolkit = getToolkit();
         Dimension screenDim =  toolkit.getScreenSize();
         Dimension frameDim = appletFrame.getSize();
         int cellSize = getCellSize();
         // Calculate new window size
         width = frameDim.width + cellSize*(shapeDim.width - gridDim.width);
         height = frameDim.height + cellSize*(shapeDim.height - gridDim.height);
         // Does it fit on the screen?
         if ( width > screenDim.width || height > screenDim.height ) {
           // With current cellSize, it doesn't fit on the screen
           // GameOfLifeControls.SIZE_SMALL corresponds with GameOfLifeControls.SMALL
           int newCellSize = GameOfLifeControls.SIZE_SMALL;
           width = frameDim.width + newCellSize*shapeDim.width - cellSize*gridDim.width;
           height = frameDim.height + newCellSize*shapeDim.height - cellSize*gridDim.height;
           // a little kludge to prevent de window from resizing twice
           // setNewCellSize only has effect at the next resize
           gameOfLifeCanvas.setAfterWindowResize( shape, newCellSize );
           // The UI has to be adjusted, too
           controls.setZoom( GameOfLifeControls.SMALL );
         } else {
           // Now resize the window (and optionally set the new cellSize)
           gameOfLifeCanvas.setAfterWindowResize( shape, cellSize );
         }
         if ( width < 400 )
           width = 400;
         appletFrame.setSize( width, height );
         return;
       }
       try {
         gameOfLifeCanvas.setShape( shape );
       } catch (ShapeException e) {
         // ignore
       }
     }
Member Data Documentation
final String org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.FILE_EXTENSION = ".cells"
Definition at line 255 of file StandaloneGameOfLife.java.
String org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.filename private
Definition at line 257 of file StandaloneGameOfLife.java.
GameOfLifeGrid org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.grid private
Definition at line 256 of file StandaloneGameOfLife.java.
Referenced by org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.GameOfLifeGridIO().
The documentation for this class was generated from the following file:
StandaloneGameOfLife.java