Game-of-Life-WSU-CEG4180: org.bitstorm.gameoflife.ShapeCollection Class Reference
org.bitstorm.gameoflife.ShapeCollection Class Reference
Static Public Member Functions
static Shape[] getShapes ()
static Shape getShapeByName (String name) throws ShapeException
Static Package Functions
[static initializer]
Static Private Attributes
static final Shape CLEAR
static final Shape GLIDER
static final Shape SMALLEXPL
static final Shape EXPLODER
static final Shape CELL10
static final Shape FISH
static final Shape PUMP
static final Shape SHOOTER
static final Shape[] COLLECTION
Detailed Description
Contains some nice Game Of Life shapes.
Author
Edwin Martin
Definition at line 14 of file ShapeCollection.java.
Member Function Documentation
org.bitstorm.gameoflife.ShapeCollection.[static initializer] () static package
static Shape org.bitstorm.gameoflife.ShapeCollection.getShapeByName (String name) throws ShapeException static
Get shape by its name.
Parameters
name name of shape
Returns
shape object
Exceptions
ShapeException if no shape with this name exist
Definition at line 53 of file ShapeCollection.java.
References org.bitstorm.gameoflife.ShapeCollection.getShapes().
Referenced by org.bitstorm.gameoflife.GameOfLife.init(), org.bitstorm.gameoflife.StandaloneGameOfLife.readShape(), and org.bitstorm.gameoflife.GameOfLife.shapeSelected().
{
     Shape[] shapes = getShapes();
     for ( int i = 0; i < shapes.length; i++ ) {
       if ( shapes[i].getName().equals( name )  )
         return shapes[i];
     }
     throw ( new ShapeException("Unknown shape: "+name) );
   }
static Shape [] org.bitstorm.gameoflife.ShapeCollection.getShapes () static
Get array of shapes.
It's not tamper-proof, but that's okay.
Returns
collection of shapes
Definition at line 43 of file ShapeCollection.java.
References org.bitstorm.gameoflife.ShapeCollection.COLLECTION.
Referenced by org.bitstorm.gameoflife.GameOfLifeControls.GameOfLifeControls(), and org.bitstorm.gameoflife.ShapeCollection.getShapeByName().
{
     return COLLECTION;
   }
Member Data Documentation
final Shape org.bitstorm.gameoflife.ShapeCollection.CELL10 static private
Definition at line 19 of file ShapeCollection.java.
final Shape org.bitstorm.gameoflife.ShapeCollection.CLEAR static private
Definition at line 15 of file ShapeCollection.java.
final Shape [] org.bitstorm.gameoflife.ShapeCollection.COLLECTION static private
Definition at line 23 of file ShapeCollection.java.
Referenced by org.bitstorm.gameoflife.ShapeCollection.getShapes().
final Shape org.bitstorm.gameoflife.ShapeCollection.EXPLODER static private
Definition at line 18 of file ShapeCollection.java.
final Shape org.bitstorm.gameoflife.ShapeCollection.FISH static private
Definition at line 20 of file ShapeCollection.java.
final Shape org.bitstorm.gameoflife.ShapeCollection.GLIDER static private
Definition at line 16 of file ShapeCollection.java.
final Shape org.bitstorm.gameoflife.ShapeCollection.PUMP static private
Definition at line 21 of file ShapeCollection.java.
final Shape org.bitstorm.gameoflife.ShapeCollection.SHOOTER static private
Definition at line 22 of file ShapeCollection.java.
final Shape org.bitstorm.gameoflife.ShapeCollection.SMALLEXPL static private
Definition at line 17 of file ShapeCollection.java.
The documentation for this class was generated from the following file:
ShapeCollection.java