Game-of-Life-WSU-CEG4180: org.bitstorm.util.AlertBox Class Reference
org.bitstorm.util.AlertBox Class Reference
Public Member Functions
AlertBox (Frame parent, String title, String message)
void processEvent (AWTEvent e)
Private Member Functions
void close ()
Private Attributes
Button okButton
Detailed Description
AlertBox shows a message besides a warning symbol.
Author
Edwin Martin
Definition at line 33 of file AlertBox.java.
Constructor & Destructor Documentation
org.bitstorm.util.AlertBox.AlertBox (Frame parent, String title, String message)
Contructs a AlertBox.
Use the newline character '
' in the message to seperate lines.
Parameters
parent parent frame
title title of the dialog box
message the message to show
Definition at line 45 of file AlertBox.java.
References org.bitstorm.util.AlertBox.close().
{
     super( parent, title, false );
     Image alertImage = Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("alert.gif"));
     ImageComponent alertImageComponent = new ImageComponent( alertImage );
     okButton = new Button(" OK ");
     okButton.addActionListener(
       new ActionListener() {
         public void actionPerformed(ActionEvent e) {
           close();
         }
       }
     );
     Panel buttonPanel = new Panel();
     buttonPanel.setLayout( new FlowLayout( FlowLayout.CENTER ) );
     buttonPanel.add( okButton );
     StringTokenizer st = new StringTokenizer( message, "\n" );
     Panel messagePanel = new Panel( new GridLayout( st.countTokens(), 1 ) );
     while ( st.hasMoreTokens() ) {
       messagePanel.add( new Label( st.nextToken() ) );
     }
     add( "West", alertImageComponent );
     add( "Center", messagePanel );
     add( "South", buttonPanel );
     enableEvents(Event.WINDOW_DESTROY);
     setResizable( false );
     setModal( true );
     pack();
     Point p = parent.getLocation();
     Dimension dim = parent.getSize();
     setLocation( p.x+dim.width/2-150, p.y+dim.height/2-75 );
     show();
   }
Member Function Documentation
void org.bitstorm.util.AlertBox.close () private
Close dialog box.
Definition at line 82 of file AlertBox.java.
Referenced by org.bitstorm.util.AlertBox.AlertBox(), and org.bitstorm.util.AlertBox.processEvent().
{
     this.hide();
     this.dispose();
   }
void org.bitstorm.util.AlertBox.processEvent (AWTEvent e)
Process close window button.
See also
java.awt.Component::processEvent(java.awt.AWTEvent)
Definition at line 90 of file AlertBox.java.
References org.bitstorm.util.AlertBox.close().
{
     if ( e.getID() == Event.WINDOW_DESTROY )
       close();
   }
Member Data Documentation
Button org.bitstorm.util.AlertBox.okButton private
Definition at line 34 of file AlertBox.java.
The documentation for this class was generated from the following file:
AlertBox.java