Game-of-Life-WSU-CEG4180: org.bitstorm.gameoflife.AppletFrame Class Reference
org.bitstorm.gameoflife.AppletFrame Class Reference
Public Member Functions
AppletFrame (String title, StandaloneGameOfLife applet)
void processEvent (AWTEvent e)
Private Member Functions
void showAboutDialog ()
void showManualDialog ()
void showLicenseDialog ()
StandaloneGameOfLife getStandaloneGameOfLife ()
Private Attributes
final GameOfLife applet
Detailed Description
The window with the applet. Extra is the menu bar.
Author
Edwin Martin
Definition at line 486 of file StandaloneGameOfLife.java.
Constructor & Destructor Documentation
org.bitstorm.gameoflife.AppletFrame.AppletFrame (String title, StandaloneGameOfLife applet)
Constructor.
Parameters
title title of window
applet applet to show
Definition at line 493 of file StandaloneGameOfLife.java.
References org.bitstorm.gameoflife.AppletFrame.applet, org.bitstorm.gameoflife.StandaloneGameOfLife.getGameOfLifeGridIO(), org.bitstorm.gameoflife.AppletFrame.getStandaloneGameOfLife(), org.bitstorm.gameoflife.StandaloneGameOfLife.init(), org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.openShape(), org.bitstorm.gameoflife.StandaloneGameOfLife.readShape(), org.bitstorm.gameoflife.GameOfLife.reset(), org.bitstorm.gameoflife.StandaloneGameOfLife.GameOfLifeGridIO.saveShape(), org.bitstorm.gameoflife.AppletFrame.showAboutDialog(), org.bitstorm.gameoflife.AppletFrame.showLicenseDialog(), and org.bitstorm.gameoflife.AppletFrame.showManualDialog().
{
         super( title );
     this.applet = applet;
     URL iconURL = this.getClass().getResource("icon.gif");
     Image icon = Toolkit.getDefaultToolkit().getImage( iconURL );
     this.setIconImage( icon );
     enableEvents(Event.WINDOW_DESTROY);
         MenuBar menubar = new MenuBar();
         Menu fileMenu = new Menu("File", true);
     MenuItem readMenuItem = new MenuItem( "Open...");
     readMenuItem.addActionListener(
       new ActionListener() {
         public synchronized void actionPerformed(ActionEvent e) {
           getStandaloneGameOfLife().getGameOfLifeGridIO().openShape();
           getStandaloneGameOfLife().reset();
         }
       }
     );
     MenuItem writeMenuItem = new MenuItem( "Save...");
     writeMenuItem.addActionListener(
       new ActionListener() {
         public synchronized void actionPerformed(ActionEvent e) {
           getStandaloneGameOfLife().getGameOfLifeGridIO().saveShape();
         }
       }
     );
     MenuItem quitMenuItem = new MenuItem( "Exit");
     quitMenuItem.addActionListener(
       new ActionListener() {
         public synchronized void actionPerformed(ActionEvent e) {
           System.exit(0);
         }
       }
     );
     Menu helpMenu = new Menu("Help", true);
     MenuItem manualMenuItem = new MenuItem( "Manual");
     manualMenuItem.addActionListener(
       new ActionListener() {
         public synchronized void actionPerformed(ActionEvent e) {
           showManualDialog();
         }
       }
     );
     MenuItem licenseMenuItem = new MenuItem( "License");
     licenseMenuItem.addActionListener(
       new ActionListener() {
         public synchronized void actionPerformed(ActionEvent e) {
           showLicenseDialog();
         }
       }
     );
      MenuItem aboutMenuItem = new MenuItem( "About");
     aboutMenuItem.addActionListener(
       new ActionListener() {
         public synchronized void actionPerformed(ActionEvent e) {
           showAboutDialog();
         }
       }
     );
         fileMenu.add(readMenuItem);
     fileMenu.add(writeMenuItem);
     fileMenu.addSeparator();
     fileMenu.add(quitMenuItem);
     helpMenu.add(manualMenuItem);
     helpMenu.add(licenseMenuItem);
     helpMenu.add(aboutMenuItem);
         menubar.add(fileMenu);
     menubar.add(helpMenu);
         GridBagLayout gridbag = new GridBagLayout();
         GridBagConstraints appletContraints = new GridBagConstraints();
         setLayout(gridbag);
         appletContraints.fill = GridBagConstraints.BOTH;
         appletContraints.weightx = 1;
         appletContraints.weighty = 1;
         gridbag.setConstraints(applet, appletContraints);
         setMenuBar(menubar);
     setResizable(true);
         add(applet);
         Toolkit screen = getToolkit();
         Dimension screenSize = screen.getScreenSize();
         // Java in Windows opens windows in the upper left corner, which is ugly! Center instead.
         if ( screenSize.width >= 640 && screenSize.height >= 480 )
           setLocation((screenSize.width-550)/2, (screenSize.height-400)/2);
     applet.init( this );
     applet.start();
     pack();
     // Read shape after initialization
     applet.readShape();
     // Bring to front. Sometimes it stays behind other windows.
         show();
     toFront();
     }
Member Function Documentation
StandaloneGameOfLife org.bitstorm.gameoflife.AppletFrame.getStandaloneGameOfLife () private
Get StandaloneGameOfLife object.
Returns
StandaloneGameOfLife
Definition at line 633 of file StandaloneGameOfLife.java.
References org.bitstorm.gameoflife.AppletFrame.applet.
Referenced by org.bitstorm.gameoflife.AppletFrame.AppletFrame().
{
     return (StandaloneGameOfLife) applet;
   }
void org.bitstorm.gameoflife.AppletFrame.processEvent (AWTEvent e)
Process close window button.
See also
java.awt.Component::processEvent(java.awt.AWTEvent)
Definition at line 597 of file StandaloneGameOfLife.java.
{
     if ( e.getID() == Event.WINDOW_DESTROY )
       System.exit(0);
   }
void org.bitstorm.gameoflife.AppletFrame.showAboutDialog () private
Show about dialog.
Definition at line 605 of file StandaloneGameOfLife.java.
Referenced by org.bitstorm.gameoflife.AppletFrame.AppletFrame().
{
     Properties properties = System.getProperties();
     String jvmProperties = "Java VM "+properties.getProperty("java.version")+" from "+properties.getProperty("java.vendor");
     Point p = getLocation();
         new AboutDialog( this, "About the Game of Life", new String[] {"Version 1.5 - Copyright 1996-2004 Edwin Martin", "http://www.bitstorm.org/gameoflife/", jvmProperties}, "about.jpg", p.x+100, p.y+60 );
     }
void org.bitstorm.gameoflife.AppletFrame.showLicenseDialog () private
Show license.
Definition at line 623 of file StandaloneGameOfLife.java.
Referenced by org.bitstorm.gameoflife.AppletFrame.AppletFrame().
{
     Point p = getLocation();
     new TextFileDialog( this, "Game of Life License", "license.txt", p.x+60, p.y+60 );
   }
void org.bitstorm.gameoflife.AppletFrame.showManualDialog () private
Show manual.
Definition at line 615 of file StandaloneGameOfLife.java.
Referenced by org.bitstorm.gameoflife.AppletFrame.AppletFrame().
{
     Point p = getLocation();
     new TextFileDialog( this, "Game of Life Manual", "manual.txt",  p.x+60, p.y+60 );
   }
Member Data Documentation
final GameOfLife org.bitstorm.gameoflife.AppletFrame.applet private
Definition at line 487 of file StandaloneGameOfLife.java.
Referenced by org.bitstorm.gameoflife.AppletFrame.AppletFrame(), and org.bitstorm.gameoflife.AppletFrame.getStandaloneGameOfLife().
The documentation for this class was generated from the following file:
StandaloneGameOfLife.java