Game-of-Life-WSU-CEG4180: org.bitstorm.gameoflife.CellGrid Interface Reference
org.bitstorm.gameoflife.CellGrid Interface Reference
Public Member Functions
boolean getCell (int col, int row)
void setCell (int col, int row, boolean cell)
Dimension getDimension ()
void resize (int col, int row)
Enumeration getEnum ()
void clear ()
Detailed Description
Interface between GameOfLifeCanvas and GameOfLife. This way GameOfLifeCanvas is generic, independent of GameOfLife. It contains generic methods to operate on a cell grid.
Author
Edwin Martin
Definition at line 22 of file CellGrid.java.
Member Function Documentation
void org.bitstorm.gameoflife.CellGrid.clear ()
Clears grid.
Implemented in org.bitstorm.gameoflife.GameOfLifeGrid.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.setShape().
boolean org.bitstorm.gameoflife.CellGrid.getCell (int col, int row)
Get status of cell (alive or dead).
Parameters
col x-position
row y-position
Returns
living or not
Implemented in org.bitstorm.gameoflife.GameOfLifeGrid.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.saveCellUnderMouse().
Dimension org.bitstorm.gameoflife.CellGrid.getDimension ()
Get dimension of cellgrid.
Returns
dimension
Implemented in org.bitstorm.gameoflife.GameOfLifeGrid.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.getPreferredSize(), org.bitstorm.gameoflife.CellGridCanvas.paint(), and org.bitstorm.gameoflife.CellGridCanvas.setShape().
Enumeration org.bitstorm.gameoflife.CellGrid.getEnum ()
Get cell-enumerator. Enumerates over all living cells (type Cell).
Returns
Enumerator over Cell.
See also
Cell
Implemented in org.bitstorm.gameoflife.GameOfLifeGrid.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.paint().
void org.bitstorm.gameoflife.CellGrid.resize (int col, int row)
Resize the cell grid.
Parameters
col new number of columns.
row new number of rows.
Implemented in org.bitstorm.gameoflife.GameOfLifeGrid.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.resized().
void org.bitstorm.gameoflife.CellGrid.setCell (int col, int row, boolean cell)
Set status of cell (alive or dead).
Parameters
col x-position
row y-position
cell living or not
Implemented in org.bitstorm.gameoflife.GameOfLifeGrid.
Referenced by org.bitstorm.gameoflife.CellGridCanvas.draw(), and org.bitstorm.gameoflife.CellGridCanvas.setShape().
The documentation for this interface was generated from the following file:
CellGrid.java