# -*- mode: org -*-
#+DATE: 2018-12-05
#+TITLE: Kotlin v Java
#+AUTHOR: Prabhaker Mateti
#+DESCRIPTION: CS7140 Adv Software Engineering
#+HTML_LINK_UP: ../
#+HTML_LINK_HOME: ../../../Top/index.html
#+HTML_HEAD: <style> P {text-align: justify} code, pre {color: brown;} @media screen {BODY {margin: 10%} }</style>
#+BIND: org-html-preamble-format (("en" "<a href=\"../../\"> ../../</a>"))
#+BIND: org-html-postamble-format (("en" "<hr size=1>Copyright &copy; 2018 &bull; <a href=\"http://www.wright.edu/~pmateti\"> www.wright.edu/~pmateti</a>  %d"))
#+STARTUP:showeverything
#+OPTIONS: toc:nil

* What is Kotlin?

1. Kotlin is a statically typed programming language.  An improvement
   over Java.  FOSS.
1. Can be compiled to Java Virtual Machine and also can be compiled to
   JavaScript source code or use the LLVM compiler
   infrastructure.
1. Kotlin uses aggressive type inference to determine the types of
   values and expressions.

1. Recommended by Android SDK.

1. https://en.wikipedia.org/wiki/Kotlin_(programming_language)

* Java v Kotlin

1. https://www.educba.com/java-vs-kotlin/ {pm: Side by side comparison
   of Java v Kotlin.  Pretty good.}

1. Lecture based on this.  See section titled "Java vs Kotlin
   Comparison Table".

* Kotlin Example: LCM and GCD

https://rosettacode.org/

  #+begin_src kotlin
fun main(args: Array<String>) {
    fun gcd(a: Int, b: Int): Int = if (b == 0) a else gcd(b, a % b)
    fun lcm(a: Int, b: Int) = a * b / gcd(a, b)
    println(lcm(15, 9))
}
#+end_src

Forgive the math liberties that the code above takes!

* Kotlin Example: QuickSort

https://rosettacode.org/wiki/Sorting_algorithms/Quicksort#Kotlin

  #+begin_src kotlin
import java.util.*
import java.util.Comparator
 
fun <T> quickSort(a: List<T>, c: Comparator<T>): ArrayList<T> {
    if (a.isEmpty()) return ArrayList(a)
 
    val boxes = Array(3, { ArrayList<T>() })
    fun normalise(i: Int) = i / Math.max(1, Math.abs(i))
    a.forEach { boxes[normalise(c.compare(it, a[ 0])) + 1].add(it) }
    arrayOf(0, 2).forEach { boxes[it] = quickSort(boxes[it], c) }
    return boxes.flatMapTo(ArrayList<T>()) { it }
}
#+end_src

* Kotlin Example: QuickSort, v2

  #+begin_src kotlin
fun <T : Comparable<T>> quicksort(list: List<T>): List<T> {
    if (list.isEmpty()) return emptyList()
 
    val head = list.first()
    val tail = list.takeLast(list.size - 1)
 
    val (less, high) = tail.partition { it < head }
 
    return less + head + high
}
 
fun main(args: Array<String>) {
    val nums = listOf(9, 7, 9, 8, 1, 2, 3, 4, 1, 9, 8, 9, 2, 4, 2, 4, 6, 3)
    println(quicksort(nums))
}
#+end_src

* Kotlin Example: Fifteen Puzzle

1. https://rosettacode.org/wiki/15_Puzzle_Game Introduces the
   15-puzzle played on a 4x4 square panel.

1. The code is shown in a variety of languages.

1. [[https://rosettacode.org/wiki/15_Puzzle_Game#Kotlin][Kotlin]] version
1. [[https://rosettacode.org/wiki/15_Puzzle_Game#Java][Java]] version

* Other Kotlin Examples

1. https://try.kotlinlang.org/ {Browser based interpreter of Kotlin.}

1. https://www.programiz.com/kotlin-programming/examples {pm: As
   algorithms, poorly done.}

* Kotlin FAQ

1.  Can kotlin use Java libraries?  Yes.

1.  What is Kotlin Java?  Officially, names of two languages.  Very
    close to each other semantically.  Kotlin is far more compact than
    Java, syntactically.  Eliminates a few areas of [[https://proandroiddev.com/kotlin-avoids-entire-categories-of-java-defects-89f160ba4671][classic sources of
    bugs]].

1. Can kotlin replace Java? Yes.

1. Does kotlin compile to Java? Yes, it can compile into JVM byte
   code.  Kotlin, Scala and Java can compile to native assembly/
   machine code.

1. https://kotlinlang.org/docs/reference/faq.html

* References

1. https://www.educba.com/java-vs-kotlin/ {pm: Side by side comparison of
   Java v Kotlin.  Pretty good.}  Required Reading.
1. https://github.com/JetBrains/kotlin-examples  Reference.

* End
# Local variables:
# after-save-hook: org-html-export-to-html
# end:

