# -*- mode: org -*-
# -*- org-export-html-postamble:t; -*-
#+STARTUP:showeverything
#+TITLE: Fall 2013: Home Work 2
#+AUTHOR: Prabhaker Mateti
#+OPTIONS: toc:nil
#+LINK_HOME: ../../
#+LINK_UP: ../../Lectures
#+DESCRIPTION: CS7140 Software Engineering Lecture
#+BIND: org-export-html-preamble-format (("en" "<a href=\"../../Top/\">CS 7140 Advanced Software Engineering</a>"))
#+BIND: org-export-html-postamble-format (("en" "<hr size=1>Copyright &copy; 2013 %e &bull; <a href=\"http://www.wright.edu/~pmateti\">www.wright.edu/~pmateti</a>"))
#+STYLE: <style> P {text-align: justify} code {font-family: monospace; font-size: 10pt;color: brown;} @media screen {BODY {margin: 10%} }</style>

Home work in this course is done individually, without help from
others.  The due date is announced on the course home page.

We will be using the SmallSet.java ([[../Lectures/FormalMethods/SmallSet.java][Java Source]], [[../Lectures/FormalMethods/SmallSet.java.html][htmlized]], [[../Lectures/FormalMethods/SmallSet.java.pdf][pdf]]) file
in a couple of the items below.  You are welcome to use /your/ version
of SmallSet.java instead.

1. (25 points) [Literate Programming] Express SmallSet.Java as a
   literate program (LP).  The LP version should exemplify the OOP
   design by contract principles.  Recall that an LP author presents
   it in an order that suits the explanation of the program to fellow
   software engineers, not necessarily in the order that a compiler
   may expect it.

   You may use any of the LP tools: [[http://www.cs.tufts.edu/~nr/noweb/][noweb]], [[http://nuweb.sourceforge.net/][nuweb]], cweb, [[http://wiki.eclipse.org/Intent][intent]], [[http://lep.sourceforge.net/][lep]]
   (Eclipse plugin), [[https://code.google.com/p/nano-lp/][nano-lp]], ...; some of these are ready to =apt-get
   install= packages in Debian/Ubuntu distros.  Visit
   http://www.literateprogramming.com/ for further details.  Professor
   Emeritus Donald Knuth, "fastest pen in the West", Turing Award
   Winner 1974, developer of the [[http://en.wikipedia.org/wiki/TeX][TeX]] typesetting system, has several
   example programs at
   http://www-cs-faculty.stanford.edu/~knuth/programs.html to read.
   His "Programming Pearls, Literate Programming: The Common Words
   Problem", [[http://www2.ece.ohio-state.edu/~fasiha/Papers/CommACM-Programming-Pearls-Knuth-Bentley-v29-n5-1986.pdf][PDF]], 1986 was a Required Reading weeks ago.

1. (25 points) [JML] This part of the home work is focussed on gaining
   experience with the use of JML.  Thoroughly document SmallSet.Java
   using JML assertions (i.e., invariant, requires, ensures,
   assignable, ...).  Recall that we want the weakest =requires=, and
   the strongest =ensures= and invariants.

   Use a JML Plugin (in Eclipse, or Intellij Idea) or a command line
   JML tool to runtime assertion check (RAC) the SmallSet.Java.  There
   are several JML plugins that you can discover through a web search;
   e.g., [[http://jmlspecs.sourceforge.net/openjml-updatesite]] It is
   useful to this class if you all try different JML plugins and
   report on your experience.

1. (25 points) [JUnit or TestNG] This part of the home work is
   focussed on systematic testing.  You are welcome to use any two
   BlueJ class files, non-trivial, and intersting-to-you, as test
   targets.  Members of a team must select different classes.  You are
   welcome to include the results of this Homework2 in the Testing and
   Debugging Report of the course project.

   Use a JUnit Plugin or a TestNG plugin (in Eclipse, or Intellij
   Idea).  The latest versions of these IDE already have these test
   plugins installed.

1. (25 points) [FindBugs Plugin] This part of the home work is
   focussed on gaining experience with the use of a static analysis of
   source code tool named [[http://findbugs.sourceforge.net/][FindBugs]]. See also,
   [[http://plugins.jetbrains.com/plugin/?id=3847][http://plugins. jetbrains. com/ plugin/ ?id=3847]].  You are welcome
   to use any two BlueJ class files, non-trivial, and
   intersting-to-you, as targets.  Members of a team must select
   different classes.  Examine closely the reports produced by the
   FindBugs tool.  Which of the items do you agree with?  How did you
   resolve it?

1. (00 points) Please maintain a journal for this homework.  Submit a
   summary.

This =Homework2= is now complete. 
Turn in your answers on =gandalf.cs.wright.edu= as in
  =~pmateti/cs7140/turnin Homework2 hw2.pdf tarBallName= Include the
  source code files into the tar-ball.  Other than the source code
  files, put *everything else*, including diagrams, screen shots,
  together and produce one .pdf file.
 
