WhiteBoard Using RMI: WhiteBoard.LinesFrameImpl Class Reference
WhiteBoard.LinesFrameImpl Class Reference
Public Member Functions
LinesFrameImpl (String[] args) throws Exception
void recvOneLine (LineCoords ln)
Static Public Member Functions
static void main (String[] args)
Package Attributes
WindowListener destroyWindow
MouseListener getCoords
String myCLientURL
WindowListener raisedWindow
int x1
int y0 = 0
int y1
Static Package Attributes
static final int HEIGHT = 300
Private Member Functions
void deleteAndExit ()
Private Attributes
Frame frame
String myURL
WbClient myWbClient
int x0 = 0
Static Private Attributes
static final int WIDTH = 300
Detailed Description
Definition at line 12 of file LinesFrameImpl.java.
Constructor & Destructor Documentation
WhiteBoard.LinesFrameImpl.LinesFrameImpl (String[] args) throws Exception [inline]
Definition at line 62 of file LinesFrameImpl.java.
References WhiteBoard.LinesFrameImpl.destroyWindow, WhiteBoard.LinesFrameImpl.frame, WhiteBoard.LinesFrameImpl.getCoords, WhiteBoard.LinesFrameImpl.HEIGHT, WhiteBoard.Invoke.lookup(), WhiteBoard.Invoke.makeURL(), WhiteBoard.LinesFrameImpl.myCLientURL, WhiteBoard.Invoke.myPrint(), WhiteBoard.LinesFrameImpl.myURL, WhiteBoard.LinesFrameImpl.myWbClient, WhiteBoard.LinesFrameImpl.raisedWindow, WhiteBoard.WbClient.recvDisplayObj(), and WhiteBoard.LinesFrameImpl.WIDTH.
Referenced by WhiteBoard.LinesFrameImpl.main().
{
        // args = [myId, bnm, displayMcnm, clientMcnm, clientId]
        super();
        myCLientURL = Invoke.makeURL('C', args[4]);
        frame = new Frame(args[1] + "@" + myCLientURL + "@" + args[3]);
        frame.setSize(WIDTH, HEIGHT);
        frame.setVisible(true);
        frame.addWindowListener(destroyWindow);
        frame.addWindowListener(raisedWindow);
        frame.addMouseListener(getCoords);
        myURL = Invoke.makeURL('D', args[4]);
        myWbClient = (WbClient) Invoke.lookup(myCLientURL);
        myWbClient.recvDisplayObj(this);
        Invoke.myPrint("LinesFrameImpl", myURL);
        Invoke.myPrint("LinesFrameImpl", ""+myWbClient);
        Invoke.myPrint("LinesFrameImpl", "Done");
    }
Member Function Documentation
void WhiteBoard.LinesFrameImpl.deleteAndExit () [inline, private]
Definition at line 22 of file LinesFrameImpl.java.
References WhiteBoard.LinesFrameImpl.myURL, WhiteBoard.LinesFrameImpl.myWbClient, and WhiteBoard.WbClient.pleaseDie().
{
        try {
            myWbClient.pleaseDie();
            Naming.unbind(myURL);
        } catch (Exception e) {e.printStackTrace();}
        System.exit(0);
    }
static void WhiteBoard.LinesFrameImpl.main (String[] args) [inline, static]
Definition at line 89 of file LinesFrameImpl.java.
References WhiteBoard.LinesFrameImpl.LinesFrameImpl().
{
        try {   LinesFrameImpl f = new LinesFrameImpl(args); }
        catch (Exception e) {e.printStackTrace();}
    }
void WhiteBoard.LinesFrameImpl.recvOneLine (LineCoords ln) [inline]
Implements WhiteBoard.LinesFrame.
Definition at line 83 of file LinesFrameImpl.java.
References WhiteBoard.LineCoords.c, WhiteBoard.LinesFrameImpl.frame, WhiteBoard.LineCoords.x1, WhiteBoard.LineCoords.x2, WhiteBoard.LineCoords.y1, and WhiteBoard.LineCoords.y2.
{
        Graphics g = frame.getGraphics();
        g.setColor(ln.c);
        g.drawLine(ln.x1, ln.y1, ln.x2, ln.y2);
    }
Member Data Documentation
WindowListener WhiteBoard.LinesFrameImpl.destroyWindow [package]
Initial value:
 new WindowAdapter() {
            public void windowClosing(WindowEvent w) {
                deleteAndExit();
            }
        }
Definition at line 30 of file LinesFrameImpl.java.
Referenced by WhiteBoard.LinesFrameImpl.LinesFrameImpl().
Frame WhiteBoard.LinesFrameImpl.frame [private]
Definition at line 18 of file LinesFrameImpl.java.
Referenced by WhiteBoard.LinesFrameImpl.LinesFrameImpl(), and WhiteBoard.LinesFrameImpl.recvOneLine().
MouseListener WhiteBoard.LinesFrameImpl.getCoords [package]
Initial value:
 new MouseAdapter() {
            public void mouseClicked(MouseEvent m) {
                if (m.getModifiers() == InputEvent.BUTTON3_MASK)
                    deleteAndExit();
                try {
                    LineCoords ln = new LineCoords();
                    ln.x2 = m.getX();
                    ln.y2 = m.getY();
                    ln.x1 = x0;
                    ln.y1 = y0;
                    x0 = ln.x2;
                    y0 = ln.y2;
                    myWbClient.sendLine(ln);
                } catch (Exception e) {e.printStackTrace();}
            }
        }
Definition at line 43 of file LinesFrameImpl.java.
Referenced by WhiteBoard.LinesFrameImpl.LinesFrameImpl().
final int WhiteBoard.LinesFrameImpl.HEIGHT = 300 [static, package]
Definition at line 17 of file LinesFrameImpl.java.
Referenced by WhiteBoard.LinesFrameImpl.LinesFrameImpl().
String WhiteBoard.LinesFrameImpl.myCLientURL [package]
Definition at line 20 of file LinesFrameImpl.java.
Referenced by WhiteBoard.LinesFrameImpl.LinesFrameImpl().
String WhiteBoard.LinesFrameImpl.myURL [private]
Definition at line 20 of file LinesFrameImpl.java.
Referenced by WhiteBoard.LinesFrameImpl.deleteAndExit(), and WhiteBoard.LinesFrameImpl.LinesFrameImpl().
WbClient WhiteBoard.LinesFrameImpl.myWbClient [private]
Definition at line 19 of file LinesFrameImpl.java.
Referenced by WhiteBoard.LinesFrameImpl.deleteAndExit(), and WhiteBoard.LinesFrameImpl.LinesFrameImpl().
WindowListener WhiteBoard.LinesFrameImpl.raisedWindow [package]
Initial value:
 new WindowAdapter() {
            public void windowActivated(WindowEvent w) {
                try { myWbClient.sendAllLines(); }
                catch (Exception e) {e.printStackTrace();}
            }
        }
Definition at line 36 of file LinesFrameImpl.java.
Referenced by WhiteBoard.LinesFrameImpl.LinesFrameImpl().
final int WhiteBoard.LinesFrameImpl.WIDTH = 300 [static, private]
Definition at line 17 of file LinesFrameImpl.java.
Referenced by WhiteBoard.LinesFrameImpl.LinesFrameImpl().
int WhiteBoard.LinesFrameImpl.x0 = 0 [private]
Definition at line 16 of file LinesFrameImpl.java.
int WhiteBoard.LinesFrameImpl.x1 [package]
Definition at line 16 of file LinesFrameImpl.java.
int WhiteBoard.LinesFrameImpl.y0 = 0 [package]
Definition at line 16 of file LinesFrameImpl.java.
int WhiteBoard.LinesFrameImpl.y1 [package]
Definition at line 16 of file LinesFrameImpl.java.
The documentation for this class was generated from the following file:
LinesFrameImpl.java