WhiteBoard Using RMI: WhiteBoard.Invoke Class Reference
WhiteBoard.Invoke Class Reference
Static Public Member Functions
static void javaVM (char c, String args)
Invoke java on the given class in a separate process.
static Remote lookup (String url)
static void main (String[] args)
static String makeURL (char c, String id)
static void myPrint (String who, String what)
static String promptAndGet (String msg)
static void setJavaCmdPath (String s)
Static Public Attributes
static int verbosity = 1
Static Private Attributes
static final String classNames [] = {serverClass, clientClass,linesClass}
static final String clientClass = "WhiteBoard.WbClientImpl"
static String javaCmd = "java"
The following Srings isolate path related issues.
static final String linesClass = "WhiteBoard.LinesFrameImpl"
static int pid = 0
static final String rmiRegistryPfx = "//localhost/"
static final String serverClass = "WhiteBoard.WbServerImpl"
static BufferedReader stdIn
Detailed Description
Definition at line 8 of file Invoke.java.
Member Function Documentation
static void WhiteBoard.Invoke.javaVM (char c, String args) [inline, static]
Invoke java on the given class in a separate process.
Also, take care of any exceptions.
Definition at line 54 of file Invoke.java.
References WhiteBoard.Invoke.classNames, WhiteBoard.Invoke.javaCmd, WhiteBoard.Invoke.myPrint(), and WhiteBoard.Invoke.pid.
Referenced by WhiteBoard.WbAdmin.addClientReq(), WhiteBoard.Invoke.main(), WhiteBoard.WbClientImpl.makeMyLinesFrame(), and WhiteBoard.WbAdmin.serverCreate().
{
        pid ++;
        String classNm = classNames[c == 'S'? 0 : c == 'C' ? 1 : 2];
        String cmd = javaCmd + " " +  classNm + " " + pid + " " +  args;
        try {
            Runtime r = Runtime.getRuntime();
            myPrint("Runtime "  + r, cmd);
            try {
                Process p = r.exec(cmd);
                myPrint("Process", "" + p);
            } catch(Exception e) {
                System.out.println("Error executing r.exec(" + cmd + ")");
            }
        } catch(Exception e) {
            System.out.println("Runtime Error executing [" + cmd + "]");
        }
    }
static Remote WhiteBoard.Invoke.lookup (String url) [inline, static]
Definition at line 77 of file Invoke.java.
References WhiteBoard.Invoke.myPrint().
Referenced by WhiteBoard.LinesFrameImpl.LinesFrameImpl(), and WhiteBoard.WbClientImpl.WbClientImpl().
{
        for (int j = 0; j < 10; j++)
            try {
                return Naming.lookup(url);
            } catch (Exception e) {
                myPrint("Naming.lookup(", url + ") not found yet ...");
                try {Thread.sleep(1000);}
                catch (Exception x)  {x.printStackTrace();}
            }
        return null;
    }
static void WhiteBoard.Invoke.main (String[] args) [inline, static]
Definition at line 89 of file Invoke.java.
References WhiteBoard.Invoke.javaVM().
{
        Invoke.javaVM('S', "");
    }
static String WhiteBoard.Invoke.makeURL (char c, String id) [inline, static]
Definition at line 73 of file Invoke.java.
References WhiteBoard.Invoke.rmiRegistryPfx.
Referenced by WhiteBoard.LinesFrameImpl.LinesFrameImpl(), WhiteBoard.WbClientImpl.WbClientImpl(), and WhiteBoard.WbServerImpl.WbServerImpl().
{
        return rmiRegistryPfx + c + id;
    }
static void WhiteBoard.Invoke.myPrint (String who, String what) [inline, static]
Definition at line 31 of file Invoke.java.
References WhiteBoard.Invoke.verbosity.
Referenced by WhiteBoard.Invoke.javaVM(), WhiteBoard.LinesFrameImpl.LinesFrameImpl(), WhiteBoard.Invoke.lookup(), WhiteBoard.WbServerImpl.pleaseDie(), WhiteBoard.WbClientImpl.pleaseDie(), WhiteBoard.WbClientImpl.recvDisplayObj(), WhiteBoard.WbClientImpl.WbClientImpl(), and WhiteBoard.WbServerImpl.WbServerImpl().
{
        if (verbosity > 0)
            System.out.println(who + ": " + what);
    }
static String WhiteBoard.Invoke.promptAndGet (String msg) [inline, static]
Definition at line 37 of file Invoke.java.
References WhiteBoard.Invoke.stdIn.
Referenced by WhiteBoard.WbAdmin.addClientReq(), WhiteBoard.WbAdmin.serverCreate(), and WhiteBoard.WbAdmin.userInteract().
{
        if (stdIn == null)
            stdIn = new BufferedReader(new InputStreamReader(System.in));
        String s = null;
        try {
            System.out.print(msg + ": ");
            System.out.flush();
            s = stdIn.readLine();
        } catch (Exception e) {e.printStackTrace();}
        if (s == null || s == "") s = "empty";
        return s;
    }
static void WhiteBoard.Invoke.setJavaCmdPath (String s) [inline, static]
Definition at line 26 of file Invoke.java.
References WhiteBoard.Invoke.javaCmd.
{
        javaCmd = s;
    }
Member Data Documentation
final String WhiteBoard.Invoke.classNames[] = {serverClass, clientClass,linesClass} [static, private]
Definition at line 24 of file Invoke.java.
Referenced by WhiteBoard.Invoke.javaVM().
final String WhiteBoard.Invoke.clientClass = "WhiteBoard.WbClientImpl" [static, private]
Definition at line 21 of file Invoke.java.
String WhiteBoard.Invoke.javaCmd = "java" [static, private]
The following Srings isolate path related issues.
Definition at line 15 of file Invoke.java.
Referenced by WhiteBoard.Invoke.javaVM(), and WhiteBoard.Invoke.setJavaCmdPath().
final String WhiteBoard.Invoke.linesClass = "WhiteBoard.LinesFrameImpl" [static, private]
Definition at line 22 of file Invoke.java.
int WhiteBoard.Invoke.pid = 0 [static, private]
Definition at line 11 of file Invoke.java.
Referenced by WhiteBoard.Invoke.javaVM().
final String WhiteBoard.Invoke.rmiRegistryPfx = "//localhost/" [static, private]
Definition at line 19 of file Invoke.java.
Referenced by WhiteBoard.Invoke.makeURL().
final String WhiteBoard.Invoke.serverClass = "WhiteBoard.WbServerImpl" [static, private]
Definition at line 20 of file Invoke.java.
BufferedReader WhiteBoard.Invoke.stdIn [static, private]
Definition at line 10 of file Invoke.java.
Referenced by WhiteBoard.Invoke.promptAndGet().
int WhiteBoard.Invoke.verbosity = 1 [static]
Definition at line 9 of file Invoke.java.
Referenced by WhiteBoard.Invoke.myPrint().
The documentation for this class was generated from the following file:
Invoke.java