WhiteBoard Using RMI: WhiteBoard.WbServerImpl Class Reference
WhiteBoard.WbServerImpl Class Reference
Public Member Functions
void addClient (WbClient wc, String brdnm) throws java.rmi.RemoteException
void addLine (LineCoords ln, String brdnm) throws java.rmi.RemoteException
void delClient (WbClient wc, String brdnm) throws java.rmi.RemoteException
void sendAllLines (WbClient wc, String brdnm) throws java.rmi.RemoteException
WbServerImpl (String[] args) throws Exception
Static Public Member Functions
static void main (String args[])
Private Member Functions
ABoard findAboard (String brdnm)
void pleaseDie ()
void sendAllLines (WbClient wc, ABoard ab)
Private Attributes
String myURL
Vector< ABoard > vBoards
Detailed Description
Definition at line 22 of file WbServerImpl.java.
Constructor & Destructor Documentation
WhiteBoard.WbServerImpl.WbServerImpl (String[] args) throws Exception [inline]
Definition at line 29 of file WbServerImpl.java.
References WhiteBoard.Invoke.makeURL(), WhiteBoard.Invoke.myPrint(), WhiteBoard.WbServerImpl.myURL, and WhiteBoard.WbServerImpl.vBoards.
Referenced by WhiteBoard.WbServerImpl.main().
{
        // args = [serverID, serverMcnm]
        vBoards = new Vector <ABoard> ();
        myURL = Invoke.makeURL('S', args[0]);
        Naming.rebind(myURL, this); // rmi register ourselves
        Invoke.myPrint("WbServerImpl", myURL + " started");
    }
Member Function Documentation
void WhiteBoard.WbServerImpl.addClient (WbClient wc, String brdnm) throws java.rmi.RemoteException [inline]
Implements WhiteBoard.WbServer.
Definition at line 72 of file WbServerImpl.java.
References WhiteBoard.WbServerImpl.findAboard(), WhiteBoard.WbServerImpl.sendAllLines(), WhiteBoard.WbServerImpl.vBoards, and WhiteBoard.ABoard.vClients.
{
        ABoard ab = findAboard(brdnm);
        if (ab == null) {
            ab = new ABoard(brdnm);
            vBoards.addElement(ab);
        } else {
            sendAllLines(wc, ab); // new client on an old board
        }
        ab.vClients.addElement(wc);
    }
void WhiteBoard.WbServerImpl.addLine (LineCoords ln, String brdnm) throws java.rmi.RemoteException [inline]
Implements WhiteBoard.WbServer.
Definition at line 98 of file WbServerImpl.java.
References WhiteBoard.WbServerImpl.findAboard(), WhiteBoard.WbClient.updateBoard(), WhiteBoard.ABoard.vClients, and WhiteBoard.ABoard.vLines.
{
        ABoard ab = findAboard(brdnm);
        if (ab == null) return;
        ab.vLines.addElement(ln);
        // Broadcast to all the clients on this board
        for (Enumeration e = ab.vClients.elements(); e.hasMoreElements();) {
            WbClient wc = (WbClient) e.nextElement();
            try {wc.updateBoard(ln);}
            catch (Exception x) {x.printStackTrace();}
        }
    }
void WhiteBoard.WbServerImpl.delClient (WbClient wc, String brdnm) throws java.rmi.RemoteException [inline]
Implements WhiteBoard.WbServer.
Definition at line 84 of file WbServerImpl.java.
References WhiteBoard.WbServerImpl.findAboard(), WhiteBoard.WbServerImpl.pleaseDie(), WhiteBoard.WbServerImpl.vBoards, and WhiteBoard.ABoard.vClients.
{
        ABoard ab = findAboard(brdnm);
        if (ab == null) return;
        ab.vClients.removeElement(wc);
        // If this is the last client in board, delete board
        if (ab.vClients.size() == 0) vBoards.removeElement(ab);
        // If this was the last board, terminate this server
        if (vBoards.size() == 0) pleaseDie();
    }
ABoard WhiteBoard.WbServerImpl.findAboard (String brdnm) [inline, private]
Definition at line 50 of file WbServerImpl.java.
References WhiteBoard.ABoard.boardName, and WhiteBoard.WbServerImpl.vBoards.
Referenced by WhiteBoard.WbServerImpl.addClient(), WhiteBoard.WbServerImpl.addLine(), WhiteBoard.WbServerImpl.delClient(), and WhiteBoard.WbServerImpl.sendAllLines().
{
        for (Enumeration e = vBoards.elements(); e.hasMoreElements();) {
            ABoard b = (ABoard) e.nextElement();
            if (brdnm.equals(b.boardName))
                return b;
        }
        return null;
    }
static void WhiteBoard.WbServerImpl.main (String args[]) [inline, static]
Definition at line 113 of file WbServerImpl.java.
References WhiteBoard.WbServerImpl.WbServerImpl().
{
        try { WbServerImpl wsi = new WbServerImpl(args);}
        catch (Exception e) {e.printStackTrace();}
    }
void WhiteBoard.WbServerImpl.pleaseDie () [inline, private]
Definition at line 37 of file WbServerImpl.java.
References WhiteBoard.Invoke.myPrint(), and WhiteBoard.WbServerImpl.myURL.
Referenced by WhiteBoard.WbServerImpl.delClient().
{
        int delay = 5000;       // in msec, delayed death
        Timer timer = new Timer();
        timer.schedule( new TimerTask(){
                public void run() {
                    try {Naming.unbind(myURL);}
                    catch (Exception e) {e.printStackTrace();}
                    Invoke.myPrint("WbServerImpl", myURL + " exits");
                    System.exit(0);
                }
            }, delay);
    }
void WhiteBoard.WbServerImpl.sendAllLines (WbClient wc, String brdnm) throws java.rmi.RemoteException [inline]
Implements WhiteBoard.WbServer.
Definition at line 59 of file WbServerImpl.java.
References WhiteBoard.WbServerImpl.findAboard().
Referenced by WhiteBoard.WbServerImpl.addClient().
{
        ABoard ab = findAboard(brdnm);
        sendAllLines(wc, ab);
    }
void WhiteBoard.WbServerImpl.sendAllLines (WbClient wc, ABoard ab) [inline, private]
Definition at line 65 of file WbServerImpl.java.
References WhiteBoard.WbClient.updateBoard(), and WhiteBoard.ABoard.vLines.
{
        for (Enumeration e = ab.vLines.elements(); e.hasMoreElements(); ) {
            try {wc.updateBoard((LineCoords) e.nextElement());}
            catch (Exception x) {x.printStackTrace();}
        }
    }
Member Data Documentation
String WhiteBoard.WbServerImpl.myURL [private]
Definition at line 27 of file WbServerImpl.java.
Referenced by WhiteBoard.WbServerImpl.pleaseDie(), and WhiteBoard.WbServerImpl.WbServerImpl().
Vector<ABoard> WhiteBoard.WbServerImpl.vBoards [private]
Definition at line 26 of file WbServerImpl.java.
Referenced by WhiteBoard.WbServerImpl.addClient(), WhiteBoard.WbServerImpl.delClient(), WhiteBoard.WbServerImpl.findAboard(), and WhiteBoard.WbServerImpl.WbServerImpl().
The documentation for this class was generated from the following file:
WbServerImpl.java