WhiteBoard Using RMI: WhiteBoard.WbClientImpl Class Reference
WhiteBoard.WbClientImpl Class Reference
Public Member Functions
void pleaseDie () throws java.rmi.RemoteException
void recvDisplayObj (LinesFrame s)
void sendAllLines () throws java.rmi.RemoteException
void sendLine (LineCoords ln)
void updateBoard (LineCoords ln) throws java.rmi.RemoteException
WbClientImpl (String[] args) throws Exception
Static Public Member Functions
static void main (String args[])
Package Attributes
String myBoardNm
String myServerURL
String myURL
Private Member Functions
void makeMyLinesFrame (String[] args) throws Exception
Private Attributes
Color myColor
LinesFrame myLinesFrame
String thisMcnm
WbServer wbServer
Detailed Description
Definition at line 10 of file WbClientImpl.java.
Constructor & Destructor Documentation
WhiteBoard.WbClientImpl.WbClientImpl (String[] args) throws Exception [inline]
Definition at line 25 of file WbClientImpl.java.
References WhiteBoard.Invoke.lookup(), WhiteBoard.WbClientImpl.makeMyLinesFrame(), WhiteBoard.Invoke.makeURL(), WhiteBoard.WbClientImpl.myBoardNm, WhiteBoard.WbClientImpl.myColor, WhiteBoard.Invoke.myPrint(), WhiteBoard.WbClientImpl.myServerURL, WhiteBoard.WbClientImpl.myURL, WhiteBoard.WbClientImpl.thisMcnm, and WhiteBoard.WbClientImpl.wbServer.
Referenced by WhiteBoard.WbClientImpl.main().
{
        // args = [clientId, brdNm, displayMcnm, wbserverURL, color]
        super();
        myBoardNm = args[1];
        myURL = Invoke.makeURL('C', args[0]);
        Naming.rebind(myURL, this);
        Invoke.myPrint("WbClientImpl", "did Naming.rebind " +  myURL);
        thisMcnm = java.net.InetAddress.getLocalHost().getHostName();
        makeMyLinesFrame(args);
        myServerURL = args[3];
        wbServer = (WbServer) Invoke.lookup(myServerURL);
        myColor = new Color(Integer.parseInt(args[4], 16));
        Invoke.myPrint("WbClient waiting for", "recvDisplayObj");
        // addClient() occurs in recvDisplayObj()
    }
Member Function Documentation
static void WhiteBoard.WbClientImpl.main (String args[]) [inline, static]
Definition at line 76 of file WbClientImpl.java.
References WhiteBoard.WbClientImpl.WbClientImpl().
{
        try {WbClientImpl me = new WbClientImpl(args);}
        catch (Exception e) {e.printStackTrace();}
    }
void WhiteBoard.WbClientImpl.makeMyLinesFrame (String[] args) throws Exception [inline, private]
Definition at line 20 of file WbClientImpl.java.
References WhiteBoard.Invoke.javaVM(), and WhiteBoard.WbClientImpl.thisMcnm.
Referenced by WhiteBoard.WbClientImpl.WbClientImpl().
{
        Invoke.javaVM
            ('L', args[1]  + " " + args[2] + " " + thisMcnm + " " + args[0]);
    }
void WhiteBoard.WbClientImpl.pleaseDie () throws java.rmi.RemoteException [inline]
Implements WhiteBoard.WbClient.
Definition at line 67 of file WbClientImpl.java.
References WhiteBoard.WbServer.delClient(), WhiteBoard.WbClientImpl.myBoardNm, WhiteBoard.Invoke.myPrint(), WhiteBoard.WbClientImpl.myURL, and WhiteBoard.WbClientImpl.wbServer.
{
        try {
            wbServer.delClient(this, myBoardNm);
            Naming.unbind(myURL);
        } catch (Exception e) {e.printStackTrace();}
        Invoke.myPrint("WbClient ", myURL + " exits");
        System.exit(0);
    }
void WhiteBoard.WbClientImpl.recvDisplayObj (LinesFrame s) [inline]
Implements WhiteBoard.WbClient.
Definition at line 60 of file WbClientImpl.java.
References WhiteBoard.WbServer.addClient(), WhiteBoard.WbClientImpl.myBoardNm, WhiteBoard.WbClientImpl.myLinesFrame, WhiteBoard.Invoke.myPrint(), and WhiteBoard.WbClientImpl.wbServer.
{
        Invoke.myPrint("WbClient waiting Ended", "" + s);
        myLinesFrame = s;
        try {wbServer.addClient(this, myBoardNm);}
        catch (Exception e) {e.printStackTrace();}
    }
void WhiteBoard.WbClientImpl.sendAllLines () throws java.rmi.RemoteException [inline]
Implements WhiteBoard.WbClient.
Definition at line 50 of file WbClientImpl.java.
References WhiteBoard.WbClientImpl.myBoardNm, WhiteBoard.WbServer.sendAllLines(), and WhiteBoard.WbClientImpl.wbServer.
{
        wbServer.sendAllLines(this, myBoardNm);
    }
void WhiteBoard.WbClientImpl.sendLine (LineCoords ln) [inline]
Implements WhiteBoard.WbClient.
Definition at line 54 of file WbClientImpl.java.
References WhiteBoard.WbServer.addLine(), WhiteBoard.LineCoords.c, WhiteBoard.WbClientImpl.myBoardNm, WhiteBoard.WbClientImpl.myColor, and WhiteBoard.WbClientImpl.wbServer.
{
        ln.c = myColor;
        try {wbServer.addLine(ln, myBoardNm);}
        catch (Exception e) {e.printStackTrace();}
    }
void WhiteBoard.WbClientImpl.updateBoard (LineCoords ln) throws java.rmi.RemoteException [inline]
Implements WhiteBoard.WbClient.
Definition at line 44 of file WbClientImpl.java.
References WhiteBoard.WbClientImpl.myLinesFrame, and WhiteBoard.LinesFrame.recvOneLine().
{
        myLinesFrame.recvOneLine(ln);
    }
Member Data Documentation
String WhiteBoard.WbClientImpl.myBoardNm [package]
Definition at line 15 of file WbClientImpl.java.
Referenced by WhiteBoard.WbClientImpl.pleaseDie(), WhiteBoard.WbClientImpl.recvDisplayObj(), WhiteBoard.WbClientImpl.sendAllLines(), WhiteBoard.WbClientImpl.sendLine(), and WhiteBoard.WbClientImpl.WbClientImpl().
Color WhiteBoard.WbClientImpl.myColor [private]
Definition at line 16 of file WbClientImpl.java.
Referenced by WhiteBoard.WbClientImpl.sendLine(), and WhiteBoard.WbClientImpl.WbClientImpl().
LinesFrame WhiteBoard.WbClientImpl.myLinesFrame [private]
Definition at line 17 of file WbClientImpl.java.
Referenced by WhiteBoard.WbClientImpl.recvDisplayObj(), and WhiteBoard.WbClientImpl.updateBoard().
String WhiteBoard.WbClientImpl.myServerURL [package]
Definition at line 15 of file WbClientImpl.java.
Referenced by WhiteBoard.WbClientImpl.WbClientImpl().
String WhiteBoard.WbClientImpl.myURL [package]
Definition at line 15 of file WbClientImpl.java.
Referenced by WhiteBoard.WbClientImpl.pleaseDie(), and WhiteBoard.WbClientImpl.WbClientImpl().
String WhiteBoard.WbClientImpl.thisMcnm [private]
Definition at line 15 of file WbClientImpl.java.
Referenced by WhiteBoard.WbClientImpl.makeMyLinesFrame(), and WhiteBoard.WbClientImpl.WbClientImpl().
WbServer WhiteBoard.WbClientImpl.wbServer [private]
Definition at line 14 of file WbClientImpl.java.
Referenced by WhiteBoard.WbClientImpl.pleaseDie(), WhiteBoard.WbClientImpl.recvDisplayObj(), WhiteBoard.WbClientImpl.sendAllLines(), WhiteBoard.WbClientImpl.sendLine(), and WhiteBoard.WbClientImpl.WbClientImpl().
The documentation for this class was generated from the following file:
WbClientImpl.java