WhiteBoard Using RMI: WhiteBoard.WbAdmin Class Reference
WhiteBoard.WbAdmin Class Reference
Public Member Functions
WbAdmin ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void addClientReq ()
void queryReq ()
void serverCreate ()
void transferReq ()
void userInteract ()
Private Attributes
Vector vServers
Static Private Attributes
static final String menu = "[s]erver, [a]dd client, [q]uery, [t]ransfer, e[x]it"
Detailed Description
Definition at line 9 of file WbAdmin.java.
Constructor & Destructor Documentation
WhiteBoard.WbAdmin.WbAdmin () [inline]
Definition at line 16 of file WbAdmin.java.
References WhiteBoard.WbAdmin.vServers.
Referenced by WhiteBoard.WbAdmin.main().
                     {
        vServers = new Vector();
    }
Member Function Documentation
void WhiteBoard.WbAdmin.addClientReq () [inline, private]
Definition at line 25 of file WbAdmin.java.
References WhiteBoard.Invoke.javaVM(), and WhiteBoard.Invoke.promptAndGet().
Referenced by WhiteBoard.WbAdmin.userInteract().
{
        String args = Invoke.promptAndGet("BoardName DisplayOn ServerURL");
        Invoke.javaVM('C', args);
    }
static void WhiteBoard.WbAdmin.main (String[] args) [inline, static]
Definition at line 51 of file WbAdmin.java.
References WhiteBoard.WbAdmin.userInteract(), and WhiteBoard.WbAdmin.WbAdmin().
{
        WbAdmin wa = new WbAdmin();
        wa.userInteract();
    }
void WhiteBoard.WbAdmin.queryReq () [inline, private]
Definition at line 34 of file WbAdmin.java.
Referenced by WhiteBoard.WbAdmin.userInteract().
{
        // Query for inforamtion from each server. For you TODO
    }
void WhiteBoard.WbAdmin.serverCreate () [inline, private]
Definition at line 20 of file WbAdmin.java.
References WhiteBoard.Invoke.javaVM(), and WhiteBoard.Invoke.promptAndGet().
Referenced by WhiteBoard.WbAdmin.userInteract().
{
        String args = Invoke.promptAndGet("ServerMachineName");
        Invoke.javaVM('S',  args);
    }
void WhiteBoard.WbAdmin.transferReq () [inline, private]
Definition at line 30 of file WbAdmin.java.
Referenced by WhiteBoard.WbAdmin.userInteract().
{
        // Transfer a white board to a new server. For you TODO
    }
void WhiteBoard.WbAdmin.userInteract () [inline, private]
Definition at line 38 of file WbAdmin.java.
References WhiteBoard.WbAdmin.addClientReq(), WhiteBoard.WbAdmin.menu, WhiteBoard.Invoke.promptAndGet(), WhiteBoard.WbAdmin.queryReq(), WhiteBoard.WbAdmin.serverCreate(), and WhiteBoard.WbAdmin.transferReq().
Referenced by WhiteBoard.WbAdmin.main().
{
        while (true) {
            String choice = Invoke.promptAndGet(menu);
            switch (choice.charAt(0)) {
            case 's': serverCreate(); break;
            case 'a': addClientReq(); break;
            case 'q': queryReq(); break;
            case 't': transferReq(); break;
            case 'x': System.exit(0); break;
            }
        }
    }
Member Data Documentation
final String WhiteBoard.WbAdmin.menu = "[s]erver, [a]dd client, [q]uery, [t]ransfer, e[x]it" [static, private]
Definition at line 13 of file WbAdmin.java.
Referenced by WhiteBoard.WbAdmin.userInteract().
Vector WhiteBoard.WbAdmin.vServers [private]
Definition at line 11 of file WbAdmin.java.
Referenced by WhiteBoard.WbAdmin.WbAdmin().
The documentation for this class was generated from the following file:
WbAdmin.java