WhiteBoard Using RMI: WhiteBoard.WbClient Interface Reference
WhiteBoard.WbClient Interface Reference
Public Member Functions
void pleaseDie () throws java.rmi.RemoteException
void recvDisplayObj (LinesFrame f) throws java.rmi.RemoteException
void sendAllLines () throws java.rmi.RemoteException
void sendLine (LineCoords ln) throws java.rmi.RemoteException
void updateBoard (LineCoords ln) throws java.rmi.RemoteException
Detailed Description
Definition at line 5 of file WbClient.java.
Member Function Documentation
void WhiteBoard.WbClient.pleaseDie () throws java.rmi.RemoteException
Implemented in WhiteBoard.WbClientImpl.
Referenced by WhiteBoard.LinesFrameImpl.deleteAndExit().
void WhiteBoard.WbClient.recvDisplayObj (LinesFrame f) throws java.rmi.RemoteException
Implemented in WhiteBoard.WbClientImpl.
Referenced by WhiteBoard.LinesFrameImpl.LinesFrameImpl().
void WhiteBoard.WbClient.sendAllLines () throws java.rmi.RemoteException
Implemented in WhiteBoard.WbClientImpl.
void WhiteBoard.WbClient.sendLine (LineCoords ln) throws java.rmi.RemoteException
Implemented in WhiteBoard.WbClientImpl.
void WhiteBoard.WbClient.updateBoard (LineCoords ln) throws java.rmi.RemoteException
Implemented in WhiteBoard.WbClientImpl.
Referenced by WhiteBoard.WbServerImpl.addLine(), and WhiteBoard.WbServerImpl.sendAllLines().
The documentation for this interface was generated from the following file:
WbClient.java