WhiteBoard Using RMI: WhiteBoard.WbServer Interface Reference
WhiteBoard.WbServer Interface Reference
Public Member Functions
void addClient (WbClient wc, String brnm) throws java.rmi.RemoteException
void addLine (LineCoords ln, String brnm) throws java.rmi.RemoteException
void delClient (WbClient wc, String brnm) throws java.rmi.RemoteException
void sendAllLines (WbClient wc, String brnm) throws java.rmi.RemoteException
Detailed Description
Definition at line 7 of file WbServer.java.
Member Function Documentation
void WhiteBoard.WbServer.addClient (WbClient wc, String brnm) throws java.rmi.RemoteException
Implemented in WhiteBoard.WbServerImpl.
Referenced by WhiteBoard.WbClientImpl.recvDisplayObj().
void WhiteBoard.WbServer.addLine (LineCoords ln, String brnm) throws java.rmi.RemoteException
Implemented in WhiteBoard.WbServerImpl.
Referenced by WhiteBoard.WbClientImpl.sendLine().
void WhiteBoard.WbServer.delClient (WbClient wc, String brnm) throws java.rmi.RemoteException
Implemented in WhiteBoard.WbServerImpl.
Referenced by WhiteBoard.WbClientImpl.pleaseDie().
void WhiteBoard.WbServer.sendAllLines (WbClient wc, String brnm) throws java.rmi.RemoteException
Implemented in WhiteBoard.WbServerImpl.
Referenced by WhiteBoard.WbClientImpl.sendAllLines().
The documentation for this interface was generated from the following file:
WbServer.java