# -*- mode: shell-script; fill-column: 75; comment-column: 50; -*-

# 2016-08-29
# This file is for use by pmateti@wright.edu, not the students.

# source this file; no shebang #!/bin/bash;
# There is a script embedded in this 00-ReadMe.txt.  It defines what
# files will be generated from what and how.  More comments at the end of
# this file

cleanUp() {
    TMPD=./RevealJS
    ls -l $TMPD/01-*
    echo echo rm $(ls $TMPD/01-*)
}


# convert one html file generated by org mode into revealjs based slides
# not elegant, but works

# $1 html file generated by org; $2 RevealJS is relative to cwd, ex: '../..'
org-revealjs() {
    [ -z $2 ] && echo '$2' RevealJS dots are empty && return
    sedpat=s:./RevealJS:$2/RevealJS:
    ofnm=${1%.html}-slides.html
    pre=$2/RevealJS/revealjs-pre.html
    post=$2/RevealJS/revealjs-post.html
    tfnm=/tmp/$1

    cp $1 /tmp/
    sed -i $tfnm -e '1,/id="content"/ d' \
        -e 's/<div /<section /' \
        -e 's:</div>:</section>:' \
        -e 's/<p><img /<img /' \
        -e 's:<section class="outline-text-2":<sectionX :' \
        -e 's:<section class="outline-text-3":<sectionX :' \
        -e ':</body>:,:</html>:d'

    sed -i $tfnm -e 's/<section id="text-table-of-contents">//'
    sed -i $tfnm -e '1i<section "id=preamble">' 
    sed -i $tfnm -e 's@/h1>@/h1><h2 style="color: black"> Prabhaker Mateti<h2><h3>Wright State University</h3><a href="http://www.cs.wright.edu/~pmateti">www.cs.wright.edu/~pmateti</a><\/section>@'
    
    cat $pre $tfnm $post > $ofnm
    sed -i $ofnm -e $sedpat
    ls -l $1 $ofnm
}

# files $pre and $post are edited versions of files from the RevealJS
# distribution.  These do contain RevealJS specific pathnames.

# sed is written up in mutiple lines because seq of -e were not
# working; need to read more on sed;

# TBD -e 's:</section>N</section>:</section>:'
# the resulting html can be cleaned up further -- but no time now


# generate *-slides.html from a *.html files produced by org-mode in these
# directories.
genSlides() {
    source ./RevealJS/revealjs.sh

    for dnm in AccessControl AppDevelop Detection Exploits Forensics \
      GetStarted Injection Internals make.sh NetAttacks \
      NewsStories PocketSpy Prevention Privacy Refreshers \
      Reversing Security
    do
        cd $dnm; pwd
        echo TBD cmd to be inserted
        ls -ld
        cd -
    done
    org-revealjs amrita-2016.html .
    ln -sf amrita-2016-slides.html index.html
    ls -l index.html
}

<< 'comment-end'

# This is 00-ReadMe.txt of CEG4440 bundle.

PDFs, unless authored by me, have been removed.  Copyright reasons.

RevealJS/ has files needed by the *-slides.html files.  The slides are
generated by the methods of revealjs.sh.  Read the RevealJS/README.md
for a how-to-use RevealJS doc.  Websearch for RevealJS.

For every *.org there should be a *.html file.

Dir/dir.org All org-mode file are created by pmateti;
Dir/dir.html Emacs Org mode generates this file from dir.org;
Dir/dir-slides.html revealjs.sh::org-revealjs() Dir/dir.html ..;
Dir/index.html sim-link to /Dir/dir-slides.html;

Naming convention: Only dirs start with upper case; ordinary file
names have hyphen separated words.
Dir/topic.org, Dir/topic.html, Dir/topic-slides.html: see make.sh.
Doing Makefile was unnecessary and more complex.

comment-end
