# -*- mode: org -*-
#+date: 2016-02-04
#+TITLE: Solitaire FreeCell 
#+AUTHOR: Prabhaker Mateti
#+DESCRIPTION: Mateti: OO Programming and Design 
#+HTML_LINK_HOME: ../../../Top/index.html
#+HTML_LINK_UP: ../
#+HTML_HEAD: <style> P,li {text-align: justify} code {color: brown;} @media screen {BODY {margin: 10%} }</style>
#+BIND: org-html-preamble-format (("en" "%d"))
#+BIND: org-html-postamble-format (("en" "<hr size=1>Copyright &copy; 2016 <a href=\"http://www.wright.edu/~pmateti\">www.wright.edu/~pmateti</a> &bull; %d"))
#+STARTUP:showeverything
#+OPTIONS: toc:nil

Abstract: This is a tiny.tiny example of software engineering
techniques applied to the classic Solitaire-Freecell.

[TBD == To Be Done]

* Links

1. JavaFX source code of Solitaire-Freecell
   1. TBD Java src code; TBD colorized
   3. You can build and run it as in =% javac Solitaire-Freecell.java; java Solitaire-Freecell=

** Links Group#2
1. https://en.wikipedia.org/wiki/FreeCell The Internet FreeCell
   Project[edit] Unsolvable combinations[edit]

1. http://freecellgamesolutions.com/ The complete set of solutions to
   the first 1,000,000 deals.  A deal is specific distribution of
   cards into piles.  Most of these deals are contributed by
   Microsoft.

1. http://rosettacode.org/wiki/Deal_cards_for_FreeCell Rosetta Code
   website has examples of source code written in many many PLs for
   various problems.

1. http://sourceforge.net/projects/freecelljsolver/ FOSS This is a
   FreeCell solitaire game solver written in the Java.  It solves all
   the first million Microsoft deals in about 4 hours -- 99.99% of
   them in less than a second, and no deal takes more than 1 minute.

1. https://github.com/sbaychev/Java/tree/master/Free-Cell/Source%20Code
   Free Cell code, images and program description. 2012

1. http://broadcast.oreilly.com/2009/01/january-column-graph-algorithm.html
   January Column: Algorithm to Solve FreeCell Solitaire Games 2009

1. http://www.jgames24.com/en/game-solutions/freecell-solutions.html
   "In order to make the solutions for freecell easily findable we
   arranged them as links of grouped freecell games. Not all the games
   have a solution. Some of them don't have a solution and some of
   them my computer can't find one. I will be playing those myself but
   this will take some time. If you have a freecell solution to a game
   that I don't have, please leave it in the comments so I can add
   it. There are some notable games. Game 1944 seems to be a hard one
   but can be solved.  Game 11982 is the only game in the original
   32000 games that is unsolvable."  They should have used "deal"
   instead of "Game".

1. http://fc-solve.shlomifish.org/links.html Freecell Solver Links

* Java GUI Frameworks

1. [[../../Languages/Java8/java-gui.org]] Java GUI Frameworks Overview
1. [[../../Languages/Java8/javaFX.org]] Intro to JavaFX.
1. Prereq: {Threads, and Event-Driven Programming}


* Solitaire-Freecell

1. Requirements of Solitaire-Freecell  [TBD]
1. Spec of Solitaire-Freecell  [TBD]
1. Design of Solitaire-Freecell  [TBD]
1. Code Documentation of Solitaire-Freecell  [TBD]

