Worms -- OOP Redo: control.cpp File Reference
control.cpp File Reference
Functions
int userControl ()
int userKeyPress (int c)
Variables
int idelay = 10
int paused = 0
int slowness
int tdelay
Function Documentation
int userControl ()
Definition at line 29 of file control.cpp.
References asogRows, EOLN, ESC, getChar, hxWorms, idelay, msg, paused, showMsg(), slowness, tdelay, and userKeyPress().
 {
   sprintf
     (msg,
      "SPC %s, ESC terminates, k kills-, w creates-, s shows-a-worm" EOLN
      "%2d Vegetarians,%2d Cannibals,%2d Scissor-heads,%2d hi-water-mark" EOLN
      "%04d slowness, - increases, + reduces, f full-speed" EOLN,
      (paused? "resumes" : "pauses "),
      nVegetarians, nCannibals, nScissors, hxWorms, slowness);
   showMsg(asogRows + 1);
   for (tdelay = slowness+1; tdelay > 0; tdelay -= idelay) {
     char c = userKeyPress(getChar()); // no-delay
     if (c == ESC) return ESC;
     if (paused) tdelay += idelay;
     if (idelay > 0)
       usleep(1000 * idelay);
   }
   return '\0';
 }
int userKeyPress (int c)
Definition at line 11 of file control.cpp.
References min, paused, random, and slowness.
Referenced by userControl().
 {
   switch (c) {
   case '+': slowness -= min(slowness, 100); break;
   case '-': slowness += 100; break;
   case 'f': slowness = 0; break;
   case 's': /* for you todo: highlight a worm */ break;
   case 'k': /* for you todo: kill the highlighted worm */ break;
   case 'w': createWorm((WORM_KIND)random(3), say[random(Nsay)]); break;
   case ' ': paused ^= 1; break;
   }
   return c;
 }
Variable Documentation
int idelay = 10
Definition at line 7 of file control.cpp.
Referenced by userControl().
int paused = 0
Definition at line 6 of file control.cpp.
Referenced by userControl(), and userKeyPress().
int slowness
Definition at line 5 of file control.cpp.
Referenced by userControl(), and userKeyPress().
int tdelay
Definition at line 8 of file control.cpp.
Referenced by userControl().