# -*- mode: org -*-
#+date: 2017-09-20
#+TITLE: Lab: Configuring a System Properly
#+AUTHOR: Prabhaker Mateti
#+HTML_LINK_HOME: ../../../Top/index.html
#+HTML_LINK_UP: ../
#+HTML_HEAD: <style> P,li {text-align: justify} code {color: brown;} @media screen {BODY {margin: 10%} }</style>
#+BIND: org-html-preamble-format (("en" "<a href=\"../../\"> ../../</a>"))
#+BIND: org-html-postamble-format (("en" "<hr size=1>Copyright &copy; 2017 <a href=\"http://www.wright.edu/~pmateti\">www.wright.edu/~pmateti</a> &bull; %d"))
#+STARTUP:showeverything
#+OPTIONS: toc:2

* Educational Objectives

Millions of machines are connected to the Internet are personal
machines running Windows and Linux with little supervision from system
administrators.  These have become targets of script kiddies. This
lecture and the associated lab experiment are intended to help
configure personal systems running Linux.

Objectives

1. Examine a Linux installation for what needs to be properly
   configured, postponing fortification and hardening to later labs.

1. Recognize that out of the box installations of OS are insecure.

1. Know the typical problem spots.

* Background

1. This lab is not net-centric; so there is no need for the NetUtils
   setup.

1. This lab asks for a certain number of fixes in the categories of
   (i) properly configured, and (ii) fortified,  (iii)
   hardening [postponing to a later lab].  

1. Write the fixes you suggest as a bash script named
   <tt>configProperly.sh</tt> that can be applied by root.  Include
   these scripts as appendices to the lab report.  These scripts can
   include commands such as <tt>wget URL</tt> or <tt>apt-get
   install/remove package</tt>.  You are welcome to use a language
   other than bash; change the file name extension accordingly.

1. Should you be unable to find such fixes, report on what you
   discovered, and stake a claim that the Linux distribution you chose
   was "so perfect".  If we discover otherwise, you will earn
   corresponding negative points.

1. Required Reading and Recopmmended Reading: See References


* Lab for 201x CEG 4420/6420

This lab gets you started on proper config.  It is not exhaustive.

1. Task: Install a Linux Distro
1. Task: DAC Examples
1. Task: Configure /etc/sudoers
1. Task: Examine suid Programs
1. Task: AppArmor and Google Chrome

* Tasks

** Task:  Install a Linux Distro

1. You will need a USB drive of 8 GB or higher capacity.  Install a
   Linux distribution of your choice, but within the Ubuntu family,
   onto the USB drive as if it is a HDD.
   1. This can be the multiboot USBD you created in an earlier lab.
      You will need to mount the system read-and-write.  The so-called
      frugal-install or ISO based installs will not do.
   2. Should you wish to work with non-Ubuntu distros, adapt the
      following appropriately.

1. Establish at least 5 ordinary users with names and passwords of
   your choice.  Learn how to to do this as a script.  Include the
   script in your submission.

1. We will refer to this installation as LXU.  Boot the PC into LXU.
   Login as needed, as an ordinary user or as root.

** Task:  DAC Examples

1. Take five examples as-is from LXU and explain DAC ideas.

** Task:  File Permissions, Etc

1. Find and report all files with peculiar permissions.  Examples: no
   permissions given =--- --- ---=, executable but not readable,
   readable for group and others but not the owner, unsearchable
   directories, etc.

1. Files and directories whose names begin with a dot are unlisted by
   ls unless -a flag is used.  Find and report all such files and
   directories whose size is larger than 10 MB.

** Task:  Check for Weak Logins

1. No password shoul be breakable within an hour.  List the names and
   plain text passwords of such users.  Assume you are root.

1. Should root be allowed to login? Ubuntu/ Debian do not assign a
   passwd to root.  Discuss the pro/cons of this choice.
1. How will you assign a password to root?
1. What is the purpose of =/etc/securetty=?  The default installed has
   many unnecessary entries.  Trim it.

** Task:  Configure /etc/sudoers

1. The =/etc/sudoers= file has a line
   : root    ALL=(ALL:ALL) ALL
   Suppose we delete this line.  What privileges does the root user lose?

1. Out of the 5 users you created (let us call them U1 .. U5), permit
   two users, U1 and U2, to be able to mount, umount only.

1. Assign two other users (U3 and U4) to group sudo.

1. Make appropriate changes so that U5 can do everything that root can.

** Task:  Examine suid Programs

1. Make a list of suid root porgrams.  The following examines only /bin.
   : find /bin -user root -perm -4000 -exec ls -li {} \; >/tmp/suid-bin.txt
1. For five of these, write a paragraph either defending its presence
   or suggesting its suid status removal.

** Task:  AppArmor and Google Chrome

1. [[https://wiki.ubuntu.com/AppArmor][AppArmor]] is a Mandatory Access Control (MAC) system. This is
   installed by default on Ubuntu systems.  Related files are at
   =/etc/apparmor*=.  Read [[https://www.howtogeek.com/118222/htg-explains-what-apparmor-is-and-how-it-secures-your-ubuntu-system/][What Is AppArmor, and How Does It Keep
   Ubuntu Secure?]] by Chris Hoffman on September 28th, 2016

1. Install Google Chrome browser for Linux.  Develop an AppArmor
   profile for Google Chrome based on the
   =/etc/apparmor.d/usr.bin.firefox= FireFox profile.  This should be
   your own work.  Include appropriate citations. Do not submit
   cut-n-paste of what you may find by googling.

** Task:  [Bonus Task] Revive Bastille Linux Script

1. https://sourceforge.net/projects/bastille-linux/ Bastille Linux is
   a proper config and Reporting/Auditing Program which enhances the
   security of a Linux box, by configuring daemons, system settings
   and firewalling. It currently functions on most major Linux
   distributions and HP-UX.  [Has been inactive for years.]

1. Make this run properly on LXU and submit the report it generates.

1. Recommended Reading:
   https://www.symantec.com/connect/articles/bastille-linux-walkthrough 2000

* TurnIn

1. Submit on Pilot into the folder L4 Config Properly
1. The Lab Report should include a section that describes the chosen
   LXU briefly, and a detailed section explaining the rationale behind
   the changes (what and why) you suggest.

* References

1. See the references of [[./index.html][Proper Configuration]].


* End
# Local variables:
# after-save-hook: org-html-export-to-html
# end:
