# -*- mode: org -*-
#+date: 2016-10-06
#+TITLE: Networking: DNS
#+AUTHOR: Prabhaker Mateti
#+HTML_LINK_UP: ../
#+HTML_HEAD: <style> P,li {text-align: justify} code {color: brown;} @media screen {BODY {margin: 10%} }</style>
#+BIND: org-html-preamble-format (("en" "<a href=\"../../\"> ../../</a>"))
#+BIND: org-html-postamble-format (("en" "<hr size=1>Copyright &copy; 2016 <a href=\"http://www.wright.edu/~pmateti\">www.wright.edu/~pmateti</a> &bull; %d"))
#+STARTUP:showeverything
#+OPTIONS: toc:2

* Domain Name Service

1. Translate a mnemonic name, e.g., www.google.com, to its IP address
   173.194.46.81

1. A very large table of two columns.  Maintained by servers.

1. Query/Reply protocol.

1. Hierarchical

** Mnemonic Value

Because of the mnemonic value, humans prefer to work with host names
such as =thor.cs.wright.edu=, rather than its IP address 130.108.2.20,
where thor is the name of the host, and cs.wright.edu is the name of
the domain the host is in.  

The primary function of DNS is to map such a name into its IP
address. The DNS name space is a tree hierarchy. The top-most subtrees
are the top level domains such as .com, .edu, .net, and .org, and the
country code domains such as .us and .in. Subtrees of these are known
as sub-domains. The leaves are the individual hosts. A fully qualified
domain name is the sequence of labels, separated by a dot, on the path
from a node to the root of the tree.

* Domain Name servers

The domain name space is maintained as a database distributed over
several *domain name servers*.  A server can delegate the maintenance of
any sub-domain to another server.  A delegated sub-domain in the DNS is
called a *zone*.  The parent server keeps track of such delegations. Each
name server has authoritative information about one or more zones. It
may also have *cached*, but non-authoritative, data about other parts of
the database. A name server marks its responses to queries as
authoritative or not.  

** Root Servers

A server whose zone is the entire tree is known
as a root server.  These are located in the United States and other
countries; visit http://www.root-servers.org .

The DNS protocol operates in one of two basic modes - lookups or zone
transfers.  Either TCP or UDP can be used to transport DNS protocol
messages, connecting to server port 53 for either. Ordinary DNS
requests can be made with TCP, though convention dictates the use of
UDP for normal operation. TCP must be used for zone transfers,
however, because of the danger of dropping records with an unreliable
delivery protocol such as UDP.

** /etc/hosts
#+begin_src bash
130.108.17.111 osisServer.osis.cs.wright.edu osisServer
130.108.17.112 osis112.cs.wright.edu osis112
130.108.17.113 osis113.cs.wright.edu osis113
130.108.18.111 osis110.cs.wright.edu osis110

192.168.17.11 Perlis.osis.cs.wright.edu osis11 Perlis
192.168.17.12 Wilkes.osis.cs.wright.edu osis12 Wilkes
192.168.17.13 Hamming.osis.cs.wright.edu osis13 Hamming
192.168.17.14 Minsky.osis.cs.wright.edu osis14 Minsky
192.168.17.15 Wilkinson.osis.cs.wright.edu osis15 Wilkinson
192.168.17.16 McCarthy.osis.cs.wright.edu osis16 McCarthy
192.168.17.17 Dijkstra.osis.cs.wright.edu osis17 Dijkstra
192.168.17.18 Bachman.osis.cs.wright.edu osis18 Bachman
192.168.17.19 Knuth.osis.cs.wright.edu osis19 Knuth
192.168.17.20 Newell.osis.cs.wright.edu osis20 Newell
#+end_src


A DNS lookup causes the network layer of the OS to examine its own
/etc/hosts file.  If not found, request each of the name servers
listed in the /etc/resolv.conf file.  

#+begin_src bash
# /etc/resolv.conf - DNS setup file
domain osis.cs.wright.edu
search osis.cs.wright.edu cs.wright.edu wright.edu
nameserver 192.168.17.111 # DSL router
nameserver 130.108.2.10
nameserver 130.108.19.25
nameserver 130.108.1.20
nameserver 130.108.128.200
nameserver 8.8.8.8	# google
nameserver 8.8.4.4	# google
nameserver 208.67.222.222 # OpenDNS
nameserver 208.67.220.220 # OpenDNS
nameserver 198.153.192.50 # Norton
nameserver 198.153.194.50 # Norton
nameserver 8.26.56.26	  # Comodo Secure DNS
nameserver 8.20.247.20	  # Comodo Secure DNS
nameserver 156.154.70.1	  # DNS Advantage.
nameserver 156.154.71.1	  # DNS Advantage.
nameserver 99.99.99.53	  # ATT ISP
nameserver 68.94.156.1	  # ATT DSL
nameserver 68.94.157.1	  # ATT DSL

#+end_src

It is possible that none of the name servers listed can find the given
name.  Each name server recursively behaves the same way: look up its
own /etc/hosts or equivalent database, and then its own name servers
in its own /etc/resolv.conf.  To speed things up, a typical name
server will cache a number of previously received answers.

Sometimes it is necessary to transfer the resource records of an
entire DNS zone.  A DNS query with Name=wright.edu, Class=IN,
Type=AXFR will trigger a zone transfer for all the host names that are
in the wright.edu domain.

The domain name service is expected to run on selected server machines
at port 53. These selected server machines are called the ``name
servers'' which are authoritative for the names of a particular
domain. All other machines describe how they resolve names in a file;
on Linux, it is /etc/resolv.conf. Typically, a client machine has a
table of host names and their IP addresses in a file called hosts. If
a host name is not found in this file, the client machine requests the
name servers listed in resolv.conf.

** Simple Scenarios

For every domain, such as wright.edu, there is only one primary name
server and any number of secondary name servers. The primary name
server is the most authoritative name server for that domain. The
secondary name servers get their information about a domain from the
primary name server. The DNS stores such information as
name-to-IP-address mappings, name servers for subdomains, mail
exchangers for hosts and domains, gateway pointers and host
information.

On Linux, study the content of =/etc/resolv.conf=

* Fully Qualified Host Name FQHN

Ex =thor.cs.wright.edu=

* DNS Cache

1. DNS lookup is time consuming.
1. Save previous answers in a table: "cache"

* DNS Cache Poisoning

1. No verification is made that the replies to our DNS queries are
   "valid".
1. Answers are simply cached.
1. Rogue DNS servers.
1. Good DNS servers answering from corrupted data bases/ poisoned caches.

* DNS Cache Poisoning Defense

See the refs.



* References

1. [[http://cecs.wright.edu/~pmateti/][Prabhaker Mateti]], Overview of TCP/IP Suite of Protocols,
   [[./TCPIP-CEG4420.ppt]], [[http://cecs.wright.edu/~pmateti/Courses/4420/NetUtils/index.html][Network Setup and Utilities]], 2014.  Required
   Reading.

1. Sooel Son and Vitaly Shmatikov, The Hitchhiker’s Guide to DNS Cache
   Poisoning,
   https://www.cs.cornell.edu/~shmat/shmat_securecomm10.pdf, 2010, 29
   pp.  Highly Recommended Reading.

* End
# Local variables:
# after-save-hook: org-html-export-to-html
# end:

