
# -*- mode: org -*-
#+date: 2017-02-06
#+TITLE: Choosing Good Passwords
#+AUTHOR: Prabhaker Mateti
#+DESCRIPTION: Mateti: Android Internals and Security
#+HTML_LINK_HOME: ../../Top/index.html
#+HTML_LINK_UP: ../
#+HTML_HEAD: <style> P,li {text-align: justify} code {color: brown;} @media screen {BODY {margin: 10%} }</style>
#+BIND: org-html-preamble-format (("en" "<a href=\"../../\"> ../../</a>"))
#+BIND: org-html-postamble-format (("en" "<hr size=1>Copyright &copy; 2017 <a href=\"http://www.wright.edu/~pmateti\">www.wright.edu/~pmateti</a> &bull; %d"))
#+STARTUP:showeverything
#+OPTIONS: toc:2

* Choosing Good Passwords

The goal is to make password cracking difficult.

1997.01.02, PA News: "A recent survey by Compaq in the financial
district of London showed that poor choices are the norm for computer
passwords there. A staggering 82% of the respondents said they used,
in order of preference, "a sexual position or abusive name for the
boss" (30%), their partner's name or nickname (16%), the name of their
favorite holiday destination (15%), sports team or player (13%), and
whatever they saw first on their desk (8%)."

** DOs and DONTs

*Don't* use the following for passwords: Your first name.  Your last
name. Your login name. Your pet's name.  Names and birth dates of
spouses, friends, relatives and friends.  Any name at all. SS
number. House number. Telephone number. Your bank PIN.  Any password
shorter than six characters.

*Don't* use the same password for all your accounts.  An attacker who
broke into one account usually discovers these other accounts by going
through the memoranda that the user keeps in his files as well as by
running keystroke loggers or simple sniffers.


*Do* use passwords of six characters or more.  Use a combination of
letters, numbers, and special characters. E.g., the following advice
is found on the web.

  
1. Think of a memorable phrase, such as "over the hills and far away,
   to grand mothers house we go."

1. Next, turn it into an acronym (including the punctuation): =othafa,tgmhwg.=

1. Add complexity by substituting numbers and symbols for letters in
   the acronym. For example, substitute 0 for o, 3 for e, 7 for t and
   the at symbol (@) for a: =07h@f@,7gmhwg.=

1. Add more complexity by capitalizing at least one letter,
   such as H. =07H@f@,7gmHwg=.

1. Finally, do not use the example password above.
  

Of course, we must be aware of password cracking/stealing procedures
in choosing passwords.
  

** Bad Common Practices

Most passwords are typed by real humans in real time.  It is
unreasonable to expect that people will choose either long passwords
("pass phrases") or difficult passwords.  Any requirement that
ultimately causes people to write passwords down on paper or in a file
defeats it.

This obvious point is lost on most system administrators and auditors.
E.g., consider the following guidelines:

"In addition to the password requirements below, please also remember
that your password is case sensitive and you should always change your
stored password on any mobile devices you use.
  
    1. 	 The password length must be 8 to 14 
    1. 	 The password must contain a letter.
    1. 	 The password must contain at least one of these special characters:0123456789^()--!$
    1. 	 Do NOT use names or common words in the dictionary.
    1. 	 Do NOT use the following symbols %#.@
    1. 	 Do NOT use the last four digits of your SSN.
    1. 	 Do NOT use your CAMPUS Account username, your first name, or your last name.
    1. 	 Do NOT use 3 or more repeated (i.e., aaa or 111) or consecutive (i.e., abc or 123) characters.

Frequently, the recycling of previously used passwords is forbidden.
This implies that the old passwords are stored somewhere.  If and when
that system is intruded, not only the current passwords but all the
old passwords are revealed.  We must realize that many users use the
same passwords on multiple systems.

* End
# Local variables:
# after-save-hook: org-html-export-to-html
# end:
