WhiteBoard Project using C RPC: client.c File Reference
client.c File Reference
#include "wb.h"
Functions
static void endtheclient (int unused)
void * callbackfromwbs_1_svc (OneLn *p)
static void readndraw (int unused)
static void exposedwindow (CLIENT *clp)
static void mousewatch (CLIENT *clp)
void startclient (int nprogram, int nversion, char *servermcnm, char *boardnm, char *xdisplaynm, char *pmcolor)
Variables
static int parentid
static int childid
static int xwinio [2]
static AddLineArg me
static CLIENT * clp
Function Documentation
callbackfromwbs_1_svc()
void* callbackfromwbs_1_svc (OneLn * p)
Definition at line 36 of file client.c.
References kill(), parentid, and xwinio.
endtheclient()
static void endtheclient (int unused) static
Definition at line 21 of file client.c.
References childid, closexwindow(), clp, kill(), me, and pmap_unset().
Referenced by startclient().
exposedwindow()
static void exposedwindow (CLIENT * clp) static
Definition at line 60 of file client.c.
References drawline(), and me.
Referenced by mousewatch().
mousewatch()
static void mousewatch (CLIENT * clp) static
Definition at line 78 of file client.c.
References exposedwindow(), me, startclient(), and trackpointer().
Referenced by startclient().
readndraw()
static void readndraw (int unused) static
Definition at line 49 of file client.c.
References drawline(), and xwinio.
Referenced by startclient().
startclient()
void startclient (int nprogram, int nversion, char * servermcnm, char * boardnm, char * xdisplaynm, char * pmcolor)
Definition at line 106 of file client.c.
References atoir(), childid, clp, endtheclient(), gethostname(), me, mousewatch(), openxwindow(), parentid, readndraw(), sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction(), sigemptyset(), and xwinio.
Referenced by mousewatch().
Variable Documentation
childid
int childid static
Definition at line 13 of file client.c.
Referenced by endtheclient(), and startclient().
clp
CLIENT* clp static
Definition at line 16 of file client.c.
Referenced by endtheclient(), main(), and startclient().
me
AddLineArg me static
Definition at line 15 of file client.c.
Referenced by endtheclient(), exposedwindow(), mousewatch(), and startclient().
parentid
int parentid static
Definition at line 13 of file client.c.
Referenced by callbackfromwbs_1_svc(), and startclient().
xwinio
int xwinio[2] static
Definition at line 14 of file client.c.
Referenced by callbackfromwbs_1_svc(), readndraw(), and startclient().