WhiteBoard Project using C RPC: server.c File Reference
server.c File Reference
#include "wb.h"
Data Structures
struct ListNode
struct AClient
struct ABoard
Typedefs
typedef struct ListNode ListNode
typedef struct AClient AClient
typedef struct ABoard ABoard
Functions
static void insert (ListNode **hdr, ListNode *p)
static void delete (ListNode **hdr, ListNode *d)
static ABoard * find_wbp (char *nm)
int * addclient_1_svc (ClientData *cd, struct svc_req *srq)
static void die (int dummy)
static void delboard (ABoard *ab)
int * delclient_1_svc (ClientData *cd, struct svc_req *srq)
int * addline_1_svc (AddLineArg *ap, struct svc_req *srq)
Linep * sendallmylines_1_svc (ClientData *cd, struct svc_req *srq)
Variables
static ABoard * boards = NULL
Typedef Documentation
ABoard
typedef struct ABoard ABoard
AClient
typedef struct AClient AClient
ListNode
typedef struct ListNode ListNode
Function Documentation
addclient_1_svc()
int* addclient_1_svc (ClientData * cd, struct svc_req * srq)
Definition at line 68 of file server.c.
References AClient::callback, AClient::clientdata, ABoard::clients, find_wbp(), insert(), and ABoard::lines.
addline_1_svc()
int* addline_1_svc (AddLineArg * ap, struct svc_req * srq)
Definition at line 166 of file server.c.
References AClient::callback, callbackfromwbs_1(), ABoard::clients, find_wbp(), insert(), ABoard::lines, and AClient::next.
delboard()
static void delboard (ABoard * ab) static
Definition at line 111 of file server.c.
References ABoard::lines.
Referenced by delclient_1_svc().
delclient_1_svc()
int* delclient_1_svc (ClientData * cd, struct svc_req * srq)
Definition at line 126 of file server.c.
References AClient::callback, AClient::clientdata, ABoard::clients, delboard(), die(), find_wbp(), AClient::next, sigaction::sa_flags, sigaction::sa_handler, sigaction::sa_mask, sigaction(), and sigemptyset().
delete()
static void delete (ListNode ** hdr, ListNode * d) static
Definition at line 21 of file server.c.
References ListNode::next.
die()
static void die (int dummy) static
Definition at line 105 of file server.c.
References pmap_unset().
Referenced by delclient_1_svc().
find_wbp()
static ABoard* find_wbp (char * nm) static
Definition at line 53 of file server.c.
References AClient::clientdata, ABoard::clients, and ABoard::next.
Referenced by addclient_1_svc(), addline_1_svc(), delclient_1_svc(), and sendallmylines_1_svc().
insert()
static void insert (ListNode ** hdr, ListNode * p) static
Definition at line 13 of file server.c.
References ListNode::next.
Referenced by addclient_1_svc(), and addline_1_svc().
sendallmylines_1_svc()
Linep* sendallmylines_1_svc (ClientData * cd, struct svc_req * srq)
Definition at line 195 of file server.c.
References find_wbp(), and ABoard::lines.
Variable Documentation
boards
ABoard* boards = NULL static
Definition at line 49 of file server.c.