WhiteBoard Project using C RPC: wb.h File Reference
wb.h File Reference
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <signal.h>
#include <rpc/rpc.h>
#include <rpc/pmap_clnt.h>
#include <errno.h>
#include <assert.h>
#include "server.h"
Data Structures
struct sigaction
Functions
void * callbackfromwbs_1 (OneLn *argp, CLIENT *clnt)
long atoir (char *p, int r)
int openxwindow (char *, char *)
void drawline (void *)
void closexwindow ()
int trackpointer (void *, int)
int gethostname (char *name, size_t len)
int pmap_unset (unsigned long, unsigned long)
int sigaction (int, const struct sigaction *, struct sigaction *)
int sigemptyset (sigset_t *set)
int kill (pid_t pid, int sig)
Function Documentation
atoir()
long atoir (char * p, int r)
Definition at line 163 of file xwindow.c.
References closexwindow(), OneLn::color, drawline(), main(), openxwindow(), trackpointer(), OneLn::x1, OneLn::x2, OneLn::y1, and OneLn::y2.
Referenced by startclient().
callbackfromwbs_1()
void* callbackfromwbs_1 (OneLn * argp, CLIENT * clnt)
Referenced by addline_1_svc().
closexwindow()
void closexwindow ()
Definition at line 73 of file xwindow.c.
References Xwindow::display.
Referenced by atoir(), and endtheclient().
drawline()
void drawline (void *)
Referenced by exposedwindow(), and readndraw().
gethostname()
int gethostname (char * name, size_t len)
Referenced by startclient().
kill()
int kill (pid_t pid, int sig)
Referenced by callbackfromwbs_1_svc(), and endtheclient().
openxwindow()
int openxwindow (char * , char *)
Referenced by startclient().
pmap_unset()
int pmap_unset (unsigned long, unsigned long)
Referenced by die(), endtheclient(), and main().
sigaction()
int sigaction (int , const struct sigaction * , struct sigaction *)
Referenced by delclient_1_svc(), and startclient().
sigemptyset()
int sigemptyset (sigset_t * set)
Referenced by delclient_1_svc(), and startclient().
trackpointer()
int trackpointer (void * , int)
Referenced by mousewatch().