WhiteBoard Project using C RPC: wbadmin.c File Reference
wbadmin.c File Reference
#include "wb.h"
Data Structures
struct BClient
struct BBoard
struct XferWBArg
Macros
#define NMSZ 50
Functions
struct BBoard * query_1 (int *unused, CLIENT *clp)
int newserver_1 (char *machineName, CLIENT *clp)
int transferwhiteboard_1 (struct XferWBArg a, CLIENT *clp)
void usage ()
int queryServer (char *snm, int prgn, CLIENT *clp)
int main (int argc, char *argv[])
Macro Definition Documentation
NMSZ
#define NMSZ 50
Definition at line 24 of file wbadmin.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 70 of file wbadmin.c.
References XferWBArg::boardnm, clp, XferWBArg::machinenm, newserver_1(), XferWBArg::nprogram, XferWBArg::nversion, queryServer(), transferwhiteboard_1(), and usage().
newserver_1()
int newserver_1 (char * machineName, CLIENT * clp)
Definition at line 34 of file wbadmin.c.
Referenced by main().
query_1()
struct BBoard* query_1 (int * unused, CLIENT * clp)
Definition at line 33 of file wbadmin.c.
Referenced by queryServer().
queryServer()
int queryServer (char * snm, int prgn, CLIENT * clp)
Definition at line 48 of file wbadmin.c.
References BClient::clientdata, BBoard::clients, BClient::next, BBoard::next, and query_1().
Referenced by main().
transferwhiteboard_1()
int transferwhiteboard_1 (struct XferWBArg a, CLIENT * clp)
Definition at line 35 of file wbadmin.c.
Referenced by main().
usage()
void usage ()
Definition at line 37 of file wbadmin.c.
Referenced by main().