WhiteBoard Project using C RPC: xwindow.c File Reference
xwindow.c File Reference
#include <stdio.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include "oneln.h"
Data Structures
struct Xwindow
Typedefs
typedef struct OneLn OneLn
Functions
int openxwindow (char dispnm[], char wintitle[])
int closexwindow (void)
void drawline (OneLn *coord)
int trackpointer (OneLn *newseg, int pending)
long atoir (char *p, int r)
Variables
static Xwindow xw
Typedef Documentation
OneLn
typedef struct OneLn OneLn
Definition at line 10 of file xwindow.c.
Function Documentation
atoir()
long atoir (char * p, int r)
Definition at line 163 of file xwindow.c.
References closexwindow(), OneLn::color, drawline(), main(), openxwindow(), trackpointer(), OneLn::x1, OneLn::x2, OneLn::y1, and OneLn::y2.
Referenced by startclient().
closexwindow()
int closexwindow (void)
Definition at line 73 of file xwindow.c.
References Xwindow::display.
Referenced by atoir(), and endtheclient().
drawline()
void drawline (OneLn * coord)
Definition at line 81 of file xwindow.c.
References OneLn::color, Xwindow::display, Xwindow::gc, Xwindow::window, OneLn::x1, OneLn::x2, OneLn::y1, and OneLn::y2.
Referenced by atoir().
openxwindow()
int openxwindow (char dispnm[], char wintitle[])
Definition at line 27 of file xwindow.c.
References Xwindow::display, Xwindow::gc, and Xwindow::window.
Referenced by atoir().
trackpointer()
int trackpointer (OneLn * newseg, int pending)
Definition at line 102 of file xwindow.c.
References Xwindow::display, OneLn::x1, OneLn::x2, OneLn::y1, and OneLn::y2.
Referenced by atoir().
Variable Documentation
xw
Xwindow xw static
Definition at line 18 of file xwindow.c.