# -*- mode: org -*-
#+DATE: 2020-08-23
#+TITLE:Welcome to CS 7140 Advanced Software Engineering
#+AUTHOR: Prabhaker Mateti
#+HTML_LINK_UP: ../
#+HTML_LINK_HOME: ../../
#+HTML_HEAD: <style> P {text-align: justify} code, pre {color: brown;} @media screen {BODY {margin: 10%} }</style>
#+BIND: org-html-preamble-format (("en" "<a href=\"../../\"> ../../</a>"))
#+BIND: org-html-postamble-format (("en" "<hr size=1><a href=\"https://cecs.wright.edu/~pmateti\"> cecs.wright.edu/~pmateti</a>  %d"))
#+STARTUP:showeverything
#+OPTIONS: toc:nil

1. Visit the Course Home Page
   https://cecs.wright.edu/~pmateti/Courses/7140 at least once a
   week.  This has links to syllabus, old exams, lecture videos +
   notes and projects/HW.

1. In the context of https://www.wright.edu/coronavirus our lectures
   are asynchronous. Per week, you are expected to watch two lecture
   videos (75 min each) and study the associated lecture notes.  I
   will be posting the lectures on Tue and Thurs.  Around noon.

1. "Office Hours" are through questions/answers posted on Pilot
   Discussion for academic matters, and through emails if they are
   personal.  As needed, we can do video chats.

1. You are expected to have taken an undergrad course on Software
   Engineering here at WSU or an equivalent course elsewhere.  I will
   try to fill you in on most of the missing background/
   prerequisites.  A survey for that purpose is posted on Pilot.

1. *Pilot Action Item* Submit the written responses to the survey on
   Pilot. In the next couple of days.

# Local variables:
# after-save-hook: org-html-export-to-html
# end:
